-- 071: Data fix — PO-55UKXR2 order-plan lines were wrong (carried extra SKUs not on the actual Cin7 PO).
-- Corrected against the Cin7 export of 26-06-2026: the real PO has 48 lines. Ben applied this to his sandbox
-- (96 -> 48, verified to match the ERP mirror exactly). This migration makes prod match regardless of its
-- current state: it UPSERTS the 48 correct lines, then DELETES any other PO-55UKXR2 line. Idempotent.
-- NOTE: cost_price values are the planner's existing costs (carried from sandbox); leave as-is.

INSERT INTO planner.purchase_order_lines (po_sku, po, sku, qty, cost_price, carton_qty, po_status) VALUES
    ('PO-55UKXR2|'||'HAIRW-SUE-IBZAGLW', 'PO-55UKXR2', 'HAIRW-SUE-IBZAGLW', 420, 1.7100, NULL, NULL),
    ('PO-55UKXR2|'||'HAIRW-SUE-MIAMI', 'PO-55UKXR2', 'HAIRW-SUE-MIAMI', 720, 1.7100, NULL, NULL),
    ('PO-55UKXR2|'||'HAIRW-SUE-OCETRES', 'PO-55UKXR2', 'HAIRW-SUE-OCETRES', 780, 1.7100, NULL, NULL),
    ('PO-55UKXR2|'||'HAIRW-WAF-CHRYBMB', 'PO-55UKXR2', 'HAIRW-WAF-CHRYBMB', 1080, 2.0300, NULL, NULL),
    ('PO-55UKXR2|'||'HAIRW-WAF-TIGPALM', 'PO-55UKXR2', 'HAIRW-WAF-TIGPALM', 1020, 2.0300, NULL, NULL),
    ('PO-55UKXR2|'||'PICNIC-DES-XL-STRIPLIFE', 'PO-55UKXR2', 'PICNIC-DES-XL-STRIPLIFE', 36, 14.6200, NULL, NULL),
    ('PO-55UKXR2|'||'PONCHK-CAB-MD-BLUE-NS', 'PO-55UKXR2', 'PONCHK-CAB-MD-BLUE-NS', 30, 4.2400, NULL, NULL),
    ('PO-55UKXR2|'||'PONCHK-CAB-SM-BLUE-NS', 'PO-55UKXR2', 'PONCHK-CAB-SM-BLUE-NS', 60, 3.8700, NULL, NULL),
    ('PO-55UKXR2|'||'PONCHK-CAB-SM-NAVY-NS', 'PO-55UKXR2', 'PONCHK-CAB-SM-NAVY-NS', 60, 3.8700, NULL, NULL),
    ('PO-55UKXR2|'||'PONCHK-KID-MD-CHECKOUT', 'PO-55UKXR2', 'PONCHK-KID-MD-CHECKOUT', 60, 4.2400, NULL, NULL),
    ('PO-55UKXR2|'||'PONCHK-KID-MD-INTOWILD', 'PO-55UKXR2', 'PONCHK-KID-MD-INTOWILD', 60, 4.2400, NULL, NULL),
    ('PO-55UKXR2|'||'PONCHK-KID-SM-CHECKOUT', 'PO-55UKXR2', 'PONCHK-KID-SM-CHECKOUT', 150, 3.8700, NULL, NULL),
    ('PO-55UKXR2|'||'PONCHK-KID-SM-INTOWILD', 'PO-55UKXR2', 'PONCHK-KID-SM-INTOWILD', 150, 3.8700, NULL, NULL),
    ('PO-55UKXR2|'||'PONCHK-SUM-MD-CSTCANDY', 'PO-55UKXR2', 'PONCHK-SUM-MD-CSTCANDY', 90, 4.2400, NULL, NULL),
    ('PO-55UKXR2|'||'TEATWL-MD-BAKEME', 'PO-55UKXR2', 'TEATWL-MD-BAKEME', 50, 1.9900, NULL, NULL),
    ('PO-55UKXR2|'||'TEATWL-MD-BIGDILL', 'PO-55UKXR2', 'TEATWL-MD-BIGDILL', 50, 1.9900, NULL, NULL),
    ('PO-55UKXR2|'||'TEATWL-MD-CTCHDAY', 'PO-55UKXR2', 'TEATWL-MD-CTCHDAY', 200, 1.9700, NULL, NULL),
    ('PO-55UKXR2|'||'TEATWL-MD-KISSCOOK', 'PO-55UKXR2', 'TEATWL-MD-KISSCOOK', 150, 1.9700, NULL, NULL),
    ('PO-55UKXR2|'||'TEATWL-MD-MTCHCRSH', 'PO-55UKXR2', 'TEATWL-MD-MTCHCRSH', 50, 1.9900, NULL, NULL),
    ('PO-55UKXR2|'||'TEATWL-MD-ROOTING', 'PO-55UKXR2', 'TEATWL-MD-ROOTING', 50, 1.9900, NULL, NULL),
    ('PO-55UKXR2|'||'TEATWL-MD-SHRIMP', 'PO-55UKXR2', 'TEATWL-MD-SHRIMP', 50, 1.9700, NULL, NULL),
    ('PO-55UKXR2|'||'TEATWL-MD-STRWPOP', 'PO-55UKXR2', 'TEATWL-MD-STRWPOP', 50, 1.9900, NULL, NULL),
    ('PO-55UKXR2|'||'TEATWL-MD-XTRSAUC', 'PO-55UKXR2', 'TEATWL-MD-XTRSAUC', 50, 1.9900, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-DES-LG-BLUSKY', 'PO-55UKXR2', 'TOWLB-DES-LG-BLUSKY', 1240, 5.2000, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-DES-LG-GRECSHR', 'PO-55UKXR2', 'TOWLB-DES-LG-GRECSHR', 680, 5.2000, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-DES-LG-MELLOW', 'PO-55UKXR2', 'TOWLB-DES-LG-MELLOW', 80, 5.2000, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-DES-LG-PNKPARA', 'PO-55UKXR2', 'TOWLB-DES-LG-PNKPARA', 840, 5.2000, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-DES-LG-PSTPIER', 'PO-55UKXR2', 'TOWLB-DES-LG-PSTPIER', 440, 5.2000, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-DES-LG-RSPROAD', 'PO-55UKXR2', 'TOWLB-DES-LG-RSPROAD', 200, 5.2000, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-DES-LG-WTRSUG', 'PO-55UKXR2', 'TOWLB-DES-LG-WTRSUG', 920, 5.2000, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-DES-XL-BLUSKY', 'PO-55UKXR2', 'TOWLB-DES-XL-BLUSKY', 900, 6.1500, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-DES-XL-GRECSHR', 'PO-55UKXR2', 'TOWLB-DES-XL-GRECSHR', 990, 6.1500, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-DES-XL-MELLOW', 'PO-55UKXR2', 'TOWLB-DES-XL-MELLOW', 270, 6.1500, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-DES-XL-PNKPARA', 'PO-55UKXR2', 'TOWLB-DES-XL-PNKPARA', 660, 6.1500, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-DES-XL-PSTPIER', 'PO-55UKXR2', 'TOWLB-DES-XL-PSTPIER', 300, 6.1500, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-DES-XL-RSPROAD', 'PO-55UKXR2', 'TOWLB-DES-XL-RSPROAD', 150, 6.1500, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-DES-XL-WTRSUG', 'PO-55UKXR2', 'TOWLB-DES-XL-WTRSUG', 540, 6.1500, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-SUM-LG-CSTCANDY', 'PO-55UKXR2', 'TOWLB-SUM-LG-CSTCANDY', 760, 5.2000, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-SUM-LG-MIAMI', 'PO-55UKXR2', 'TOWLB-SUM-LG-MIAMI', 600, 5.2000, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-SUM-XL-COLAGN', 'PO-55UKXR2', 'TOWLB-SUM-XL-COLAGN', 240, 6.1500, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-SUM-XL-CSTCANDY', 'PO-55UKXR2', 'TOWLB-SUM-XL-CSTCANDY', 810, 6.1500, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLB-SUM-XL-MIAMI', 'PO-55UKXR2', 'TOWLB-SUM-XL-MIAMI', 510, 6.1500, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLF-ESS-LG-DKBLU', 'PO-55UKXR2', 'TOWLF-ESS-LG-DKBLU', 40, 4.0400, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLF-ESS-LG-GREEN-R', 'PO-55UKXR2', 'TOWLF-ESS-LG-GREEN-R', 80, 4.0400, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLF-ESS-LG-PINK-R', 'PO-55UKXR2', 'TOWLF-ESS-LG-PINK-R', 80, 4.0400, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLF-ESS-XL-PINK-R', 'PO-55UKXR2', 'TOWLF-ESS-XL-PINK-R', 120, 4.5900, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLH-CLB-LG-PEPPNCH', 'PO-55UKXR2', 'TOWLH-CLB-LG-PEPPNCH', 40, 5.5500, NULL, NULL),
    ('PO-55UKXR2|'||'TOWLH-CLB-XL-CHRYBMB', 'PO-55UKXR2', 'TOWLH-CLB-XL-CHRYBMB', 20, 6.7100, NULL, NULL)
ON CONFLICT (po_sku) DO UPDATE SET qty = excluded.qty, cost_price = excluded.cost_price,
  carton_qty = excluded.carton_qty, po_status = excluded.po_status, updated_at = now();

DELETE FROM planner.purchase_order_lines
WHERE po = 'PO-55UKXR2' AND sku NOT IN ('HAIRW-SUE-IBZAGLW', 'HAIRW-SUE-MIAMI', 'HAIRW-SUE-OCETRES', 'HAIRW-WAF-CHRYBMB', 'HAIRW-WAF-TIGPALM', 'PICNIC-DES-XL-STRIPLIFE', 'PONCHK-CAB-MD-BLUE-NS', 'PONCHK-CAB-SM-BLUE-NS', 'PONCHK-CAB-SM-NAVY-NS', 'PONCHK-KID-MD-CHECKOUT', 'PONCHK-KID-MD-INTOWILD', 'PONCHK-KID-SM-CHECKOUT', 'PONCHK-KID-SM-INTOWILD', 'PONCHK-SUM-MD-CSTCANDY', 'TEATWL-MD-BAKEME', 'TEATWL-MD-BIGDILL', 'TEATWL-MD-CTCHDAY', 'TEATWL-MD-KISSCOOK', 'TEATWL-MD-MTCHCRSH', 'TEATWL-MD-ROOTING', 'TEATWL-MD-SHRIMP', 'TEATWL-MD-STRWPOP', 'TEATWL-MD-XTRSAUC', 'TOWLB-DES-LG-BLUSKY', 'TOWLB-DES-LG-GRECSHR', 'TOWLB-DES-LG-MELLOW', 'TOWLB-DES-LG-PNKPARA', 'TOWLB-DES-LG-PSTPIER', 'TOWLB-DES-LG-RSPROAD', 'TOWLB-DES-LG-WTRSUG', 'TOWLB-DES-XL-BLUSKY', 'TOWLB-DES-XL-GRECSHR', 'TOWLB-DES-XL-MELLOW', 'TOWLB-DES-XL-PNKPARA', 'TOWLB-DES-XL-PSTPIER', 'TOWLB-DES-XL-RSPROAD', 'TOWLB-DES-XL-WTRSUG', 'TOWLB-SUM-LG-CSTCANDY', 'TOWLB-SUM-LG-MIAMI', 'TOWLB-SUM-XL-COLAGN', 'TOWLB-SUM-XL-CSTCANDY', 'TOWLB-SUM-XL-MIAMI', 'TOWLF-ESS-LG-DKBLU', 'TOWLF-ESS-LG-GREEN-R', 'TOWLF-ESS-LG-PINK-R', 'TOWLF-ESS-XL-PINK-R', 'TOWLH-CLB-LG-PEPPNCH', 'TOWLH-CLB-XL-CHRYBMB');
