-- 150: per-size approval matrix across product dimensions.
--
-- Dimensions: 'product' (supplier-submitted sample versions — existing), 'packaging', 'polybag', 'labels'
-- (Dock & Bay-uploaded design versions). Each dimension is versioned; one version is approved per size.
--
-- 1) Tag every design/sample version with its dimension. Existing rows are 'product' (supplier samples).
ALTER TABLE planner.product_dev_samples ADD COLUMN IF NOT EXISTS dimension text NOT NULL DEFAULT 'product';

-- 2) Per size × dimension: required flag + which version is approved + packaging type (pouch/box). The 'product'
--    dimension's approval stays on product_dev_sizes.approved_sample_id (unchanged); this table holds packaging /
--    polybag / labels. 'required' is per size (each size independent).
CREATE TABLE IF NOT EXISTS planner.product_dev_size_dimensions (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  size_id            bigint NOT NULL REFERENCES planner.product_dev_sizes(id) ON DELETE CASCADE,
  dimension          text   NOT NULL,                         -- 'packaging' | 'polybag' | 'labels'
  required           boolean NOT NULL DEFAULT false,
  approved_sample_id bigint REFERENCES planner.product_dev_samples(id) ON DELETE SET NULL,
  packaging_type     text,                                    -- 'pouch' | 'box' (packaging only)
  UNIQUE (size_id, dimension)
);
CREATE INDEX IF NOT EXISTS idx_pdsd_size ON planner.product_dev_size_dimensions(size_id);
CREATE INDEX IF NOT EXISTS idx_pds_item_dim ON planner.product_dev_samples(item_ref, dimension);
