-- 181_product_dev_change_log.sql — record of change for PRODUCT development items (mirrors sample_change_log
-- mig 172 / po_change_log mig 158). Captures D&B edits to a product dev item; surfaced in the PRODUCT ▸ Timeline
-- tab, merged into the note thread in descending time order (admin-only, hideable per item).

CREATE TABLE IF NOT EXISTS planner.product_dev_change_log (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_ref   text NOT NULL,
  event      text NOT NULL,
  detail     text,
  changed_by text,
  changed_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS product_dev_change_log_ref ON planner.product_dev_change_log (item_ref, changed_at DESC);
