-- 237: v_po_finance — FLOOR completion_calc (and catch_up) at 0. When a PO's recorded start deposit exceeds its
-- (start% + completion%) of value, the completion term went NEGATIVE (e.g. PO-55USLX2: 30%+20%×56,369=28,185 but
-- 40,048 start deposit recorded → completion −11,864). A milestone can't be negative; the over-payment should
-- reduce the balance, not show as a negative completion. Fix: GREATEST(0, …) around completion_calc + catch_up.
-- Everything else identical to mig 235 (blank-deposit estimate retained). DROP+CREATE, no dependents.
-- (superseded header of mig 235 below.)
-- 235: v_po_finance — BLANK-DEPOSIT ESTIMATE. Re-creates the shared PO-finance view (base def in mig 123,
-- rebuilt from the live definition which includes later table columns) with one behavioural change: when a PO
-- draws on a deposit whose amount is BLANK (a deposit row exists for the ref but its total amount is null/0 — NOT
-- the 'NO DEPOSIT' sentinel, which has no row), the pool is treated as its ESTIMATED total = Sum over the ref's
-- open, non-complete POs of (order value x supplier start%). So each PO draws its full start deposit instead of
-- being capped at 0 (the start deposit no longer rolls into completion for a not-yet-funded deposit).
-- Real-amount deposits are byte-identical (the cap still applies). NO DEPOSIT / dangling refs untouched.
--
-- DROP + CREATE (not CREATE OR REPLACE): base does SELECT po.*, and later table columns shift the po.* order vs an
-- older-built view, which CREATE OR REPLACE rejects. No DB objects depend on this view (admin + portal read it at
-- runtime), so the drop is safe. Deploy: run BEFORE the server.mjs change (deposits/cashflow use the est too).

DROP VIEW IF EXISTS planner.v_po_finance;
CREATE VIEW planner.v_po_finance AS
 WITH base AS (
         SELECT po.po,
            po.supplier_name,
            po.supplier_id,
            po.status,
            po.shipment_ref,
            po.prod_no,
            po.batch_id,
            po.batch_date,
            po.branch,
            po.client,
            po.deposit_ref,
            po.erp_po,
            po.notes,
            po.ship_type,
            po.ship_type_overide,
            po.sea_lead_time_days,
            po.country_code,
            po.first_release_window,
            po.start_production,
            po.end_production_overide,
            po.days_production_overide,
            po.warehouse_complete_date,
            po.landing_date_overide,
            po.delivery_date_overide,
            po.balance_due_date_overide,
            po.supplier_ship_date,
            po.supplier_invoice_total,
            po.order_value_estimation,
            po.deposit_fx_rate,
            po.credit_fee_assigned,
            po.pay_start_deposit_assigned,
            po.pay_start_deposit_date,
            po.pay_completion_assigned,
            po.pay_completion_date,
            po.pay_balance_1_amount,
            po.pay_balance_1_date,
            po.created_at,
            po.updated_at,
            po.flexport_reference,
            po.start_deposit_pct_override,
            po.completion_pct_override,
            po.pay_balance_2_amount,
            po.pay_balance_2_date,
            po.container_size,
            po.production_status,
            po.production_confirmed_at,
            po.client_requirements,
            po.sales_order_ref,
            po.crossdock_skus,
            po.client_po_ref,
            po.dispatch_order_ref,
            po.final_delivery_address,
            po.credit_amount,
            po.client_deadline_date,
            po.asn_numbers,
            po.supplier_confirmed_at,
            po.supplier_confirmed_by,
            po.starred,
            po.pack_polybags,
            po.pack_polybags_notes,
            po.pack_dnb_barcodes,
            po.pack_dnb_barcodes_notes,
            po.pack_rfid_barcodes,
            po.pack_rfid_barcodes_notes,
            po.pack_dnb_carton,
            po.pack_dnb_carton_notes,
            po.pack_client_carton,
            po.pack_client_carton_notes,
            po.pack_pallet_notes,
            po.pack_other_notes,
            po.dtc_accepted_at,
            po.dtc_accepted_by,
            po.invoice_processed_date,
            po.dtc_custom,
            po.dtc_key_account,
            po.preship_not_required,
            po.approved_lines,
            s.credit_days,
            s.credit_type,
            COALESCE(po.start_deposit_pct_override,
                CASE
                    WHEN COALESCE(po.status, ''::text) !~~* '%complete%'::text AND COALESCE(po.supplier_invoice_total, lv.line_value, po.order_value_estimation, 0::numeric) < 500::numeric THEN 0::numeric
                    ELSE s.start_deposit_pct
                END, 0::numeric) AS sp,
            COALESCE(po.completion_pct_override,
                CASE
                    WHEN COALESCE(po.status, ''::text) !~~* '%complete%'::text AND COALESCE(po.supplier_invoice_total, lv.line_value, po.order_value_estimation, 0::numeric) < 500::numeric THEN 0::numeric
                    ELSE s.completion_pct
                END, 0::numeric) AS cp,
            COALESCE(lv.line_value, po.order_value_estimation) AS value_est,
            lv.line_value IS NOT NULL AS value_from_lines,
            COALESCE(po.supplier_invoice_total, lv.line_value, po.order_value_estimation, 0::numeric) AS val,
            fx.flex_id,
            fx.landing_date AS flex_landing,
            fx.arrival_date AS flex_arrival,
            fx.departure_date AS flex_departure,
            sh.landing_date AS sh_landing,
            sh.delivery_date AS sh_delivery,
            sh.departure_date AS sh_departure,
            sh.arrival_date AS sh_arrival,
            COALESCE(sh.status, ''::text) AS sh_status_raw,
            sh.mode AS sh_mode,
            sh.carrier AS sh_carrier,
            sh.carrier_ref AS sh_carrier_ref,
            fx.mode AS flex_mode,
            sh.master_po = po.po AS is_master,
            da.avail AS deposit_avail,
            da.fx_rate AS deposit_fx,
            COALESCE(fx.total_quoted_amount, fx.total_freight_cost) AS flex_quote,
            fr.cost AS freight_rate,
            tr.tax_pct,
            COALESCE(tr.base, 'landed'::text) AS tax_base_kind,
            dty.duty,
            s.production_days,
            b.sea_lead_time_days AS sea_lead,
            b.air_lead_time_days AS air_lead,
                CASE
                    WHEN lower(COALESCE(sh.mode,
                    CASE
                        WHEN fx.mode ~~* 'air%'::text THEN 'air'::text
                        ELSE NULL::text
                    END, 'sea'::text)) = 'air'::text THEN b.air_lead_time_days
                    ELSE b.sea_lead_time_days
                END AS transit_lead,
            b.country_code AS branch_country,
            erp.final_delivery_date AS erp_final_delivery_date,
            erp.erp_po_id AS erp_po_id_src,
            erp.po IS NOT NULL AS erp_present
           FROM planner.purchase_orders po
             LEFT JOIN planner.suppliers s ON s.id = po.supplier_id
             LEFT JOIN planner.branches b ON b.name = po.branch
             LEFT JOIN planner.erp_purchase_orders erp ON erp.po = po.po
             LEFT JOIN planner.shipments sh ON sh.shipment_ref = COALESCE(NULLIF(po.shipment_ref, ''::text), po.po)
             LEFT JOIN planner.import_tax_rates tr ON tr.country = COALESCE(NULLIF(po.country_code, ''::text), b.country_code)
             LEFT JOIN LATERAL ( SELECT sum(l.qty::numeric * COALESCE(( SELECT plc.final_cost
                           FROM planner.portal_line_costs plc
                          WHERE plc.po = l.po AND plc.sku = l.sku AND plc.confirmed_at IS NOT NULL AND plc.final_cost IS NOT NULL), l.cost_price,
                        CASE lower(( SELECT s_1.code
                               FROM planner.suppliers s_1
                              WHERE s_1.id = po.supplier_id OR s_1.name = po.supplier_name
                             LIMIT 1))
                            WHEN 'lx'::text THEN pr.cost_lx
                            WHEN 'xr'::text THEN pr.cost_xr
                            ELSE NULL::numeric
                        END, pr.cost)) AS line_value
                   FROM planner.purchase_order_lines l
                     LEFT JOIN planner.products pr ON pr.sku = l.sku
                  WHERE l.po = po.po) lv ON true
             LEFT JOIN LATERAL ( SELECT f.flex_id,
                    f.shipment_name,
                    f.mode,
                    f.status_description,
                    f.incoterm,
                    f.freight_type,
                    f.freight_carriers,
                    f.mbl_number,
                    f.container_numbers,
                    f.cleared_customs_date,
                    f.ams_numbers,
                    f.planned_transit_time,
                    f.actual_transit_time,
                    f.total_quoted_amount,
                    f.origin_planned_departure,
                    f.origin_estimated_departure,
                    f.origin_actual_departure,
                    f.dep_port_planned_departure,
                    f.dep_port_estimated_departure,
                    f.dep_port_actual_departure,
                    f.arr_port_actual_arrival,
                    f.arr_port_estimated_arrival,
                    f.arr_port_planned_arrival,
                    f.dest_planned_arrival,
                    f.dest_estimated_arrival,
                    f.dest_actual_arrival,
                    f.shipments_ref,
                    f.packing_date,
                    f.departure_date,
                    f.landing_date,
                    f.arrival_date,
                    f.estimated_shipment_cost,
                    f.shipments_2,
                    f.last_modified_time,
                    f.total_invoiced_amount,
                    f.customs_duty_cost,
                    f.total_freight_cost,
                    f.vat_costs,
                    f.quote_requested_date
                   FROM planner.flexport_shipments f
                  WHERE f.flex_id = po.flexport_reference OR f.shipment_name = po.po OR f.shipment_name = po.shipment_ref
                  ORDER BY (f.flex_id = po.flexport_reference) DESC NULLS LAST
                 LIMIT 1) fx ON true
             LEFT JOIN LATERAL ( SELECT (
                        CASE WHEN ( SELECT count(*) FROM planner.deposits d WHERE d.is_deposit AND d.reference = po.deposit_ref) > 0
                              AND COALESCE(( SELECT sum(d.amount) FROM planner.deposits d WHERE d.is_deposit AND d.reference = po.deposit_ref), 0::numeric) = 0::numeric
                              AND upper(COALESCE(po.deposit_ref, ''::text)) <> 'NO DEPOSIT'::text
                             THEN COALESCE(( SELECT sum(round(COALESCE(p3.supplier_invoice_total, lv3.line_value, p3.order_value_estimation, 0::numeric) * COALESCE(p3.start_deposit_pct_override, s3.start_deposit_pct, 0::numeric) / 100::numeric, 2))
                                            FROM planner.purchase_orders p3
                                              LEFT JOIN planner.suppliers s3 ON s3.id = p3.supplier_id
                                              LEFT JOIN LATERAL ( SELECT sum(l.qty::numeric * COALESCE(( SELECT plc.final_cost FROM planner.portal_line_costs plc WHERE plc.po = l.po AND plc.sku = l.sku AND plc.confirmed_at IS NOT NULL AND plc.final_cost IS NOT NULL), l.cost_price,
                                                                        CASE lower(( SELECT s_1.code FROM planner.suppliers s_1 WHERE s_1.id = p3.supplier_id OR s_1.name = p3.supplier_name LIMIT 1))
                                                                            WHEN 'lx'::text THEN pr.cost_lx WHEN 'xr'::text THEN pr.cost_xr ELSE NULL::numeric END, pr.cost)) AS line_value
                                                                    FROM planner.purchase_order_lines l LEFT JOIN planner.products pr ON pr.sku = l.sku WHERE l.po = p3.po) lv3 ON true
                                           WHERE p3.deposit_ref = po.deposit_ref AND COALESCE(p3.status, ''::text) !~~* '%complete%'::text), 0::numeric)
                             ELSE COALESCE(( SELECT sum(d.amount) FROM planner.deposits d WHERE d.is_deposit AND d.reference = po.deposit_ref), 0::numeric)
                        END) - COALESCE(( SELECT sum(COALESCE(p2.pay_start_deposit_assigned, 0::numeric)) AS sum
                           FROM planner.purchase_orders p2
                          WHERE p2.deposit_ref = po.deposit_ref), 0::numeric) AS avail,
                    ( SELECT d.xero_fx
                           FROM planner.deposits d
                          WHERE d.is_deposit AND d.reference = po.deposit_ref AND d.xero_fx IS NOT NULL
                          ORDER BY d.date_paid DESC NULLS LAST
                         LIMIT 1) AS fx_rate
                  WHERE COALESCE(po.deposit_ref, ''::text) <> ''::text) da ON true
             LEFT JOIN LATERAL ( SELECT freight_rates.cost
                   FROM planner.freight_rates
                  WHERE freight_rates.destination = COALESCE(NULLIF(po.country_code, ''::text), b.country_code) AND freight_rates.container_size = po.container_size
                 LIMIT 1) fr ON true
             LEFT JOIN LATERAL ( SELECT sum(l.qty::numeric * l.cost_price * COALESCE(dr.duty_pct, 0::numeric) / 100::numeric) AS duty
                   FROM planner.purchase_order_lines l
                     JOIN planner.products p2 ON p2.sku = l.sku
                     LEFT JOIN planner.duty_rates dr ON dr.category = p2.category AND dr.country = COALESCE(NULLIF(po.country_code, ''::text), b.country_code)
                  WHERE l.po = po.po) dty ON true
        ), calc AS (
         SELECT base.po,
            base.supplier_name,
            base.supplier_id,
            base.status,
            base.shipment_ref,
            base.prod_no,
            base.batch_id,
            base.batch_date,
            base.branch,
            base.client,
            base.deposit_ref,
            base.erp_po,
            base.notes,
            base.ship_type,
            base.ship_type_overide,
            base.sea_lead_time_days,
            base.country_code,
            base.first_release_window,
            base.start_production,
            base.end_production_overide,
            base.days_production_overide,
            base.warehouse_complete_date,
            base.landing_date_overide,
            base.delivery_date_overide,
            base.balance_due_date_overide,
            base.supplier_ship_date,
            base.supplier_invoice_total,
            base.order_value_estimation,
            base.deposit_fx_rate,
            base.credit_fee_assigned,
            base.pay_start_deposit_assigned,
            base.pay_start_deposit_date,
            base.pay_completion_assigned,
            base.pay_completion_date,
            base.pay_balance_1_amount,
            base.pay_balance_1_date,
            base.created_at,
            base.updated_at,
            base.flexport_reference,
            base.start_deposit_pct_override,
            base.completion_pct_override,
            base.pay_balance_2_amount,
            base.pay_balance_2_date,
            base.container_size,
            base.production_status,
            base.production_confirmed_at,
            base.client_requirements,
            base.sales_order_ref,
            base.crossdock_skus,
            base.client_po_ref,
            base.dispatch_order_ref,
            base.final_delivery_address,
            base.credit_amount,
            base.client_deadline_date,
            base.asn_numbers,
            base.supplier_confirmed_at,
            base.supplier_confirmed_by,
            base.starred,
            base.pack_polybags,
            base.pack_polybags_notes,
            base.pack_dnb_barcodes,
            base.pack_dnb_barcodes_notes,
            base.pack_rfid_barcodes,
            base.pack_rfid_barcodes_notes,
            base.pack_dnb_carton,
            base.pack_dnb_carton_notes,
            base.pack_client_carton,
            base.pack_client_carton_notes,
            base.pack_pallet_notes,
            base.pack_other_notes,
            base.dtc_accepted_at,
            base.dtc_accepted_by,
            base.invoice_processed_date,
            base.dtc_custom,
            base.dtc_key_account,
            base.preship_not_required,
            base.approved_lines,
            base.credit_days,
            base.credit_type,
            base.sp,
            base.cp,
            base.value_est,
            base.value_from_lines,
            base.val,
            base.flex_id,
            base.flex_landing,
            base.flex_arrival,
            base.flex_departure,
            base.sh_landing,
            base.sh_delivery,
            base.sh_departure,
            base.sh_arrival,
            base.sh_status_raw,
            base.sh_mode,
            base.sh_carrier,
            base.sh_carrier_ref,
            base.flex_mode,
            base.is_master,
            base.deposit_avail,
            base.deposit_fx,
            base.flex_quote,
            base.freight_rate,
            base.tax_pct,
            base.tax_base_kind,
            base.duty,
            base.production_days,
            base.sea_lead,
            base.air_lead,
            base.transit_lead,
            base.branch_country,
            base.erp_final_delivery_date,
            base.erp_po_id_src,
            base.erp_present,
            round(base.val * base.sp / 100::numeric, 2) AS start_calc,
            COALESCE(base.pay_start_deposit_assigned, LEAST(round(base.val * base.sp / 100::numeric, 2),
                CASE
                    WHEN COALESCE(base.deposit_ref, ''::text) <> ''::text THEN GREATEST(round(COALESCE(base.deposit_avail, 0::numeric), 2), 0::numeric)
                    ELSE round(base.val * base.sp / 100::numeric, 2)
                END)) AS start_paid,
                CASE
                    WHEN base.cp > 0::numeric THEN GREATEST(0::numeric, LEAST(round((base.sp + base.cp) / 100::numeric * base.val - COALESCE(base.pay_start_deposit_assigned, LEAST(round(base.val * base.sp / 100::numeric, 2),
                    CASE
                        WHEN COALESCE(base.deposit_ref, ''::text) <> ''::text THEN GREATEST(round(COALESCE(base.deposit_avail, 0::numeric), 2), 0::numeric)
                        ELSE round(base.val * base.sp / 100::numeric, 2)
                    END)), 2), GREATEST(round(base.val + COALESCE(base.credit_amount, 0::numeric) - COALESCE(base.pay_start_deposit_assigned, LEAST(round(base.val * base.sp / 100::numeric, 2),
                    CASE
                        WHEN COALESCE(base.deposit_ref, ''::text) <> ''::text THEN GREATEST(round(COALESCE(base.deposit_avail, 0::numeric), 2), 0::numeric)
                        ELSE round(base.val * base.sp / 100::numeric, 2)
                    END)) - COALESCE(base.pay_balance_1_amount, 0::numeric) - COALESCE(base.pay_balance_2_amount, 0::numeric), 2), 0::numeric)))
                    ELSE 0::numeric
                END AS completion_calc,
                CASE
                    WHEN base.cp > 0::numeric THEN GREATEST(0::numeric, round(base.val * base.sp / 100::numeric - COALESCE(base.pay_start_deposit_assigned, LEAST(round(base.val * base.sp / 100::numeric, 2),
                    CASE
                        WHEN COALESCE(base.deposit_ref, ''::text) <> ''::text THEN GREATEST(round(COALESCE(base.deposit_avail, 0::numeric), 2), 0::numeric)
                        ELSE round(base.val * base.sp / 100::numeric, 2)
                    END)), 2))
                    ELSE 0::numeric
                END AS catch_up,
            COALESCE(base.end_production_overide,
                CASE
                    WHEN base.start_production IS NOT NULL AND base.production_days IS NOT NULL THEN (base.start_production + ((base.production_days || ' days'::text)::interval))::date
                    ELSE NULL::date
                END) AS eff_prod_end,
            base.end_production_overide IS NULL AND base.start_production IS NOT NULL AND base.production_days IS NOT NULL AS prod_end_calc
           FROM base
        ), calc2 AS (
         SELECT calc.po,
            calc.supplier_name,
            calc.supplier_id,
            calc.status,
            calc.shipment_ref,
            calc.prod_no,
            calc.batch_id,
            calc.batch_date,
            calc.branch,
            calc.client,
            calc.deposit_ref,
            calc.erp_po,
            calc.notes,
            calc.ship_type,
            calc.ship_type_overide,
            calc.sea_lead_time_days,
            calc.country_code,
            calc.first_release_window,
            calc.start_production,
            calc.end_production_overide,
            calc.days_production_overide,
            calc.warehouse_complete_date,
            calc.landing_date_overide,
            calc.delivery_date_overide,
            calc.balance_due_date_overide,
            calc.supplier_ship_date,
            calc.supplier_invoice_total,
            calc.order_value_estimation,
            calc.deposit_fx_rate,
            calc.credit_fee_assigned,
            calc.pay_start_deposit_assigned,
            calc.pay_start_deposit_date,
            calc.pay_completion_assigned,
            calc.pay_completion_date,
            calc.pay_balance_1_amount,
            calc.pay_balance_1_date,
            calc.created_at,
            calc.updated_at,
            calc.flexport_reference,
            calc.start_deposit_pct_override,
            calc.completion_pct_override,
            calc.pay_balance_2_amount,
            calc.pay_balance_2_date,
            calc.container_size,
            calc.production_status,
            calc.production_confirmed_at,
            calc.client_requirements,
            calc.sales_order_ref,
            calc.crossdock_skus,
            calc.client_po_ref,
            calc.dispatch_order_ref,
            calc.final_delivery_address,
            calc.credit_amount,
            calc.client_deadline_date,
            calc.asn_numbers,
            calc.supplier_confirmed_at,
            calc.supplier_confirmed_by,
            calc.starred,
            calc.pack_polybags,
            calc.pack_polybags_notes,
            calc.pack_dnb_barcodes,
            calc.pack_dnb_barcodes_notes,
            calc.pack_rfid_barcodes,
            calc.pack_rfid_barcodes_notes,
            calc.pack_dnb_carton,
            calc.pack_dnb_carton_notes,
            calc.pack_client_carton,
            calc.pack_client_carton_notes,
            calc.pack_pallet_notes,
            calc.pack_other_notes,
            calc.dtc_accepted_at,
            calc.dtc_accepted_by,
            calc.invoice_processed_date,
            calc.dtc_custom,
            calc.dtc_key_account,
            calc.preship_not_required,
            calc.approved_lines,
            calc.credit_days,
            calc.credit_type,
            calc.sp,
            calc.cp,
            calc.value_est,
            calc.value_from_lines,
            calc.val,
            calc.flex_id,
            calc.flex_landing,
            calc.flex_arrival,
            calc.flex_departure,
            calc.sh_landing,
            calc.sh_delivery,
            calc.sh_departure,
            calc.sh_arrival,
            calc.sh_status_raw,
            calc.sh_mode,
            calc.sh_carrier,
            calc.sh_carrier_ref,
            calc.flex_mode,
            calc.is_master,
            calc.deposit_avail,
            calc.deposit_fx,
            calc.flex_quote,
            calc.freight_rate,
            calc.tax_pct,
            calc.tax_base_kind,
            calc.duty,
            calc.production_days,
            calc.sea_lead,
            calc.air_lead,
            calc.transit_lead,
            calc.branch_country,
            calc.erp_final_delivery_date,
            calc.erp_po_id_src,
            calc.erp_present,
            calc.start_calc,
            calc.start_paid,
            calc.completion_calc,
            calc.catch_up,
            calc.eff_prod_end,
            calc.prod_end_calc,
            COALESCE(calc.sh_departure, calc.flex_departure,
                CASE
                    WHEN calc.eff_prod_end IS NOT NULL THEN (calc.eff_prod_end + '7 days'::interval)::date
                    ELSE NULL::date
                END) AS eff_ship,
                CASE
                    WHEN calc.sh_departure IS NOT NULL THEN 'S'::text
                    WHEN calc.flex_departure IS NOT NULL THEN 'FLEX'::text
                    WHEN calc.eff_prod_end IS NOT NULL THEN 'calc'::text
                    ELSE NULL::text
                END AS ship_src
           FROM calc
        ), calc3 AS (
         SELECT calc2.po,
            calc2.supplier_name,
            calc2.supplier_id,
            calc2.status,
            calc2.shipment_ref,
            calc2.prod_no,
            calc2.batch_id,
            calc2.batch_date,
            calc2.branch,
            calc2.client,
            calc2.deposit_ref,
            calc2.erp_po,
            calc2.notes,
            calc2.ship_type,
            calc2.ship_type_overide,
            calc2.sea_lead_time_days,
            calc2.country_code,
            calc2.first_release_window,
            calc2.start_production,
            calc2.end_production_overide,
            calc2.days_production_overide,
            calc2.warehouse_complete_date,
            calc2.landing_date_overide,
            calc2.delivery_date_overide,
            calc2.balance_due_date_overide,
            calc2.supplier_ship_date,
            calc2.supplier_invoice_total,
            calc2.order_value_estimation,
            calc2.deposit_fx_rate,
            calc2.credit_fee_assigned,
            calc2.pay_start_deposit_assigned,
            calc2.pay_start_deposit_date,
            calc2.pay_completion_assigned,
            calc2.pay_completion_date,
            calc2.pay_balance_1_amount,
            calc2.pay_balance_1_date,
            calc2.created_at,
            calc2.updated_at,
            calc2.flexport_reference,
            calc2.start_deposit_pct_override,
            calc2.completion_pct_override,
            calc2.pay_balance_2_amount,
            calc2.pay_balance_2_date,
            calc2.container_size,
            calc2.production_status,
            calc2.production_confirmed_at,
            calc2.client_requirements,
            calc2.sales_order_ref,
            calc2.crossdock_skus,
            calc2.client_po_ref,
            calc2.dispatch_order_ref,
            calc2.final_delivery_address,
            calc2.credit_amount,
            calc2.client_deadline_date,
            calc2.asn_numbers,
            calc2.supplier_confirmed_at,
            calc2.supplier_confirmed_by,
            calc2.starred,
            calc2.pack_polybags,
            calc2.pack_polybags_notes,
            calc2.pack_dnb_barcodes,
            calc2.pack_dnb_barcodes_notes,
            calc2.pack_rfid_barcodes,
            calc2.pack_rfid_barcodes_notes,
            calc2.pack_dnb_carton,
            calc2.pack_dnb_carton_notes,
            calc2.pack_client_carton,
            calc2.pack_client_carton_notes,
            calc2.pack_pallet_notes,
            calc2.pack_other_notes,
            calc2.dtc_accepted_at,
            calc2.dtc_accepted_by,
            calc2.invoice_processed_date,
            calc2.dtc_custom,
            calc2.dtc_key_account,
            calc2.preship_not_required,
            calc2.approved_lines,
            calc2.credit_days,
            calc2.credit_type,
            calc2.sp,
            calc2.cp,
            calc2.value_est,
            calc2.value_from_lines,
            calc2.val,
            calc2.flex_id,
            calc2.flex_landing,
            calc2.flex_arrival,
            calc2.flex_departure,
            calc2.sh_landing,
            calc2.sh_delivery,
            calc2.sh_departure,
            calc2.sh_arrival,
            calc2.sh_status_raw,
            calc2.sh_mode,
            calc2.sh_carrier,
            calc2.sh_carrier_ref,
            calc2.flex_mode,
            calc2.is_master,
            calc2.deposit_avail,
            calc2.deposit_fx,
            calc2.flex_quote,
            calc2.freight_rate,
            calc2.tax_pct,
            calc2.tax_base_kind,
            calc2.duty,
            calc2.production_days,
            calc2.sea_lead,
            calc2.air_lead,
            calc2.transit_lead,
            calc2.branch_country,
            calc2.erp_final_delivery_date,
            calc2.erp_po_id_src,
            calc2.erp_present,
            calc2.start_calc,
            calc2.start_paid,
            calc2.completion_calc,
            calc2.catch_up,
            calc2.eff_prod_end,
            calc2.prod_end_calc,
            calc2.eff_ship,
            calc2.ship_src,
            COALESCE(calc2.sh_delivery, calc2.sh_arrival, calc2.sh_landing, calc2.flex_arrival, calc2.flex_landing,
                CASE
                    WHEN calc2.eff_ship IS NOT NULL AND calc2.transit_lead IS NOT NULL THEN (calc2.eff_ship + ((calc2.transit_lead || ' days'::text)::interval))::date
                    ELSE NULL::date
                END) AS eff_delivery,
                CASE
                    WHEN calc2.sh_delivery IS NOT NULL OR calc2.sh_arrival IS NOT NULL OR calc2.sh_landing IS NOT NULL THEN 'S'::text
                    WHEN calc2.flex_arrival IS NOT NULL OR calc2.flex_landing IS NOT NULL THEN 'FLEX'::text
                    WHEN calc2.eff_ship IS NOT NULL AND calc2.transit_lead IS NOT NULL THEN 'calc'::text
                    ELSE NULL::text
                END AS delivery_src
           FROM calc2
        ), calc4 AS (
         SELECT calc3.po,
            calc3.supplier_name,
            calc3.supplier_id,
            calc3.status,
            calc3.shipment_ref,
            calc3.prod_no,
            calc3.batch_id,
            calc3.batch_date,
            calc3.branch,
            calc3.client,
            calc3.deposit_ref,
            calc3.erp_po,
            calc3.notes,
            calc3.ship_type,
            calc3.ship_type_overide,
            calc3.sea_lead_time_days,
            calc3.country_code,
            calc3.first_release_window,
            calc3.start_production,
            calc3.end_production_overide,
            calc3.days_production_overide,
            calc3.warehouse_complete_date,
            calc3.landing_date_overide,
            calc3.delivery_date_overide,
            calc3.balance_due_date_overide,
            calc3.supplier_ship_date,
            calc3.supplier_invoice_total,
            calc3.order_value_estimation,
            calc3.deposit_fx_rate,
            calc3.credit_fee_assigned,
            calc3.pay_start_deposit_assigned,
            calc3.pay_start_deposit_date,
            calc3.pay_completion_assigned,
            calc3.pay_completion_date,
            calc3.pay_balance_1_amount,
            calc3.pay_balance_1_date,
            calc3.created_at,
            calc3.updated_at,
            calc3.flexport_reference,
            calc3.start_deposit_pct_override,
            calc3.completion_pct_override,
            calc3.pay_balance_2_amount,
            calc3.pay_balance_2_date,
            calc3.container_size,
            calc3.production_status,
            calc3.production_confirmed_at,
            calc3.client_requirements,
            calc3.sales_order_ref,
            calc3.crossdock_skus,
            calc3.client_po_ref,
            calc3.dispatch_order_ref,
            calc3.final_delivery_address,
            calc3.credit_amount,
            calc3.client_deadline_date,
            calc3.asn_numbers,
            calc3.supplier_confirmed_at,
            calc3.supplier_confirmed_by,
            calc3.starred,
            calc3.pack_polybags,
            calc3.pack_polybags_notes,
            calc3.pack_dnb_barcodes,
            calc3.pack_dnb_barcodes_notes,
            calc3.pack_rfid_barcodes,
            calc3.pack_rfid_barcodes_notes,
            calc3.pack_dnb_carton,
            calc3.pack_dnb_carton_notes,
            calc3.pack_client_carton,
            calc3.pack_client_carton_notes,
            calc3.pack_pallet_notes,
            calc3.pack_other_notes,
            calc3.dtc_accepted_at,
            calc3.dtc_accepted_by,
            calc3.invoice_processed_date,
            calc3.dtc_custom,
            calc3.dtc_key_account,
            calc3.preship_not_required,
            calc3.approved_lines,
            calc3.credit_days,
            calc3.credit_type,
            calc3.sp,
            calc3.cp,
            calc3.value_est,
            calc3.value_from_lines,
            calc3.val,
            calc3.flex_id,
            calc3.flex_landing,
            calc3.flex_arrival,
            calc3.flex_departure,
            calc3.sh_landing,
            calc3.sh_delivery,
            calc3.sh_departure,
            calc3.sh_arrival,
            calc3.sh_status_raw,
            calc3.sh_mode,
            calc3.sh_carrier,
            calc3.sh_carrier_ref,
            calc3.flex_mode,
            calc3.is_master,
            calc3.deposit_avail,
            calc3.deposit_fx,
            calc3.flex_quote,
            calc3.freight_rate,
            calc3.tax_pct,
            calc3.tax_base_kind,
            calc3.duty,
            calc3.production_days,
            calc3.sea_lead,
            calc3.air_lead,
            calc3.transit_lead,
            calc3.branch_country,
            calc3.erp_final_delivery_date,
            calc3.erp_po_id_src,
            calc3.erp_present,
            calc3.start_calc,
            calc3.start_paid,
            calc3.completion_calc,
            calc3.catch_up,
            calc3.eff_prod_end,
            calc3.prod_end_calc,
            calc3.eff_ship,
            calc3.ship_src,
            calc3.eff_delivery,
            calc3.delivery_src,
                CASE
                    WHEN calc3.sh_delivery IS NOT NULL THEN calc3.sh_delivery
                    WHEN calc3.eff_delivery IS NOT NULL THEN (calc3.eff_delivery + ((
                    CASE
                        WHEN upper(COALESCE(NULLIF(calc3.country_code, ''::text), calc3.branch_country, ''::text)) = 'DIRECT'::text AND COALESCE(NULLIF(calc3.shipment_ref, ''::text), calc3.po) = calc3.po THEN 0
                        ELSE 7
                    END || ' days'::text)::interval))::date
                    ELSE NULL::date
                END AS eff_checkin,
            COALESCE(calc3.balance_due_date_overide,
                CASE
                    WHEN calc3.val < 500::numeric AND COALESCE(calc3.status, ''::text) !~~* '%complete%'::text THEN COALESCE(calc3.invoice_processed_date, calc3.eff_ship)
                    ELSE (
                    CASE
                        WHEN calc3.credit_type = 'on_shipment'::text THEN calc3.eff_ship
                        ELSE calc3.eff_delivery
                    END + ((COALESCE(calc3.credit_days, 0) || ' days'::text)::interval))::date
                END) AS bal_due_date
           FROM calc3
        )
 SELECT po,
    supplier_name,
    supplier_id,
    status,
    shipment_ref,
    prod_no,
    batch_id,
    batch_date,
    branch,
    client,
    deposit_ref,
    erp_po,
    notes,
    ship_type,
    ship_type_overide,
    sea_lead_time_days,
    country_code,
    first_release_window,
    start_production,
    end_production_overide,
    days_production_overide,
    warehouse_complete_date,
    landing_date_overide,
    delivery_date_overide,
    balance_due_date_overide,
    supplier_ship_date,
    supplier_invoice_total,
    order_value_estimation,
    deposit_fx_rate,
    credit_fee_assigned,
    pay_start_deposit_assigned,
    pay_start_deposit_date,
    pay_completion_assigned,
    pay_completion_date,
    pay_balance_1_amount,
    pay_balance_1_date,
    created_at,
    updated_at,
    flexport_reference,
    start_deposit_pct_override,
    completion_pct_override,
    pay_balance_2_amount,
    pay_balance_2_date,
    container_size,
    production_status,
    production_confirmed_at,
    client_requirements,
    sales_order_ref,
    crossdock_skus,
    client_po_ref,
    dispatch_order_ref,
    final_delivery_address,
    credit_amount,
    client_deadline_date,
    asn_numbers,
    supplier_confirmed_at,
    supplier_confirmed_by,
    starred,
    pack_polybags,
    pack_polybags_notes,
    pack_dnb_barcodes,
    pack_dnb_barcodes_notes,
    pack_rfid_barcodes,
    pack_rfid_barcodes_notes,
    pack_dnb_carton,
    pack_dnb_carton_notes,
    pack_client_carton,
    pack_client_carton_notes,
    pack_pallet_notes,
    pack_other_notes,
    dtc_accepted_at,
    dtc_accepted_by,
    invoice_processed_date,
    dtc_custom,
    dtc_key_account,
    preship_not_required,
    approved_lines,
    credit_days,
    credit_type,
    sp,
    cp,
    value_est,
    value_from_lines,
    val,
    flex_id,
    flex_landing,
    flex_arrival,
    flex_departure,
    sh_landing,
    sh_delivery,
    sh_departure,
    sh_arrival,
    sh_status_raw,
    sh_mode,
    sh_carrier,
    sh_carrier_ref,
    flex_mode,
    is_master,
    deposit_avail,
    deposit_fx,
    flex_quote,
    freight_rate,
    tax_pct,
    tax_base_kind,
    duty,
    production_days,
    sea_lead,
    air_lead,
    transit_lead,
    branch_country,
    erp_final_delivery_date,
    erp_po_id_src,
    erp_present,
    start_calc,
    start_paid,
    completion_calc,
    catch_up,
    eff_prod_end,
    prod_end_calc,
    eff_ship,
    ship_src,
    eff_delivery,
    delivery_src,
    eff_checkin,
    bal_due_date
   FROM calc4;
