-- ============================================================================
-- planner schema — CONSOLIDATED BASELINE
-- Generated from the sandbox DB via pg_dump --schema=planner --schema-only.
-- Represents the final state of migrations 001..061 (see _archive/ for history).
--
-- USE: run this ONCE on a FRESH database to stand up the entire planner schema,
-- instead of replaying 61 incremental files. Existing databases are already
-- migrated — do NOT run this against them. New changes go in NEW numbered
-- migrations on top of this baseline (062_*, 063_*, …).
-- ============================================================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: planner; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS planner;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: air_freight_rates; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.air_freight_rates (
    id bigint NOT NULL,
    min_kg numeric NOT NULL,
    max_kg numeric NOT NULL,
    rate_per_kg numeric,
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: air_freight_rates_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.air_freight_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME planner.air_freight_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: batches; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.batches (
    batch text NOT NULL,
    batch_date date,
    first_release_window text,
    notes text
);


--
-- Name: bi_rules; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.bi_rules (
    id bigint NOT NULL,
    subcategory text NOT NULL,
    countries text[] DEFAULT '{}'::text[] NOT NULL,
    channels text[] DEFAULT '{}'::text[] NOT NULL,
    rule_text text NOT NULL,
    active boolean DEFAULT true NOT NULL,
    added_by text,
    source text DEFAULT 'airtable_backfill'::text NOT NULL,
    month integer,
    year integer,
    airtable_id text
);


--
-- Name: bi_rules_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.bi_rules ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME planner.bi_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: branches; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.branches (
    name text NOT NULL,
    country_code text,
    sea_lead_time_days integer,
    air_lead_time_days integer,
    address text,
    shipping_notes text
);


--
-- Name: buy_plan; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.buy_plan (
    id bigint NOT NULL,
    run_id bigint,
    sku text NOT NULL,
    warehouse text NOT NULL,
    plan_type text NOT NULL,
    order_month date NOT NULL,
    arrival_month date,
    order_quantity integer NOT NULL,
    is_actionable_now boolean DEFAULT false NOT NULL,
    flags text[],
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT buy_plan_plan_type_check CHECK ((plan_type = ANY (ARRAY['master_3pl'::text, 'fba_direct'::text])))
);


--
-- Name: buy_plan_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.buy_plan ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME planner.buy_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.categories (
    category text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    "grouping" text,
    description text,
    loaded_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: category_exclusions; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.category_exclusions (
    subcategory text NOT NULL,
    notes text
);


--
-- Name: products; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.products (
    sku text NOT NULL,
    product_name text,
    category text,
    subcategory text,
    market_tier text,
    core_seasonal text,
    replacement_sku text,
    source text DEFAULT 'airtable_backfill'::text NOT NULL,
    loaded_at timestamp with time zone DEFAULT now() NOT NULL,
    moq integer,
    case_pack_size integer,
    supplier text,
    production_lead_time_weeks numeric,
    china_to_uk_lead_time_weeks numeric,
    china_to_us_lead_time_weeks numeric,
    china_to_eu_lead_time_weeks numeric,
    china_to_au_lead_time_weeks numeric,
    china_to_ca_lead_time_weeks numeric,
    transfer_3pl_to_fba_lead_time_weeks numeric,
    in_planning_scope boolean DEFAULT false NOT NULL,
    awd_us numeric,
    prod_weight_uk numeric,
    uk_rt numeric,
    us_rt numeric,
    eu_rt numeric,
    available_uk_dtc boolean,
    available_uk_fba boolean,
    available_uk_b2b boolean,
    available_us_dtc boolean,
    available_us_fba boolean,
    available_us_b2b boolean,
    available_eu_dtc boolean,
    available_eu_fba boolean,
    available_eu_b2b boolean,
    available_au_dtc boolean,
    available_au_fba boolean,
    available_ca_fba boolean,
    au_rt numeric,
    ca_rt numeric,
    inventory_uk_nongrs numeric,
    inventory_us_nongrs numeric,
    main_supplier_final text,
    supplier_multiple_all text,
    status text,
    clearance text,
    colour_long text,
    parent_p1 text,
    parent_c1 text,
    size text,
    variant_image_url_final text,
    variant_type text,
    shp_upload_final text,
    shp_published_final text,
    asin text,
    "3pl_eu" text,
    "3pl_ca" text,
    "3pl_au" text,
    "3pl_uk" text,
    "3pl_us" text,
    created_minutes text,
    product_name_final text,
    product_ean text,
    discontinue_date_final text,
    launch_date_overide_ws text,
    release_window text,
    amz_clear_stock text,
    listings_include text,
    discontinue_date_au_final text,
    amz_scope_of_launch_country_list text,
    core_products text,
    marketing_category_final text,
    shp_scope_of_launch_country_list text,
    products text,
    product_select_name text,
    product_category text,
    launch_date_uk text,
    launch_date_us text,
    launch_date_eu text,
    launch_date_au text,
    launch_date_ws text,
    carton_qty text,
    target_cover_overide text,
    target_cover_weeks_au_fba_from text,
    target_cover_weeks_eu_fba_from text,
    target_cover_weeks_us_fba_from text,
    target_cover_weeks_uk_fba_from text,
    target_cover_weeks_eu_3pl_from text,
    target_cover_weeks_au_3pl_from text,
    target_cover_weeks_us_3pl_from text,
    target_cover_weeks_uk_3pl_from text,
    target_cover_weeks_ca_fba_from text,
    launch_date_uk_final text,
    launch_date_au_final text,
    product_scope text,
    notes text,
    is_core text,
    fba_transfer_min_units_uk text,
    fba_transfer_min_units_us text,
    fba_transfer_min_units_eu text,
    fba_transfer_min_units_au text,
    fba_transfer_min_units_ca text,
    discontinue_date_ca text,
    launch_date_ca_retail text,
    from_replacement_sku text,
    target_cover_weeks_uk_3pl_from_category text,
    target_cover_weeks_uk_fba_from_category text,
    target_cover_weeks_us_3pl_from_category text,
    target_cover_weeks_us_fba_from_category text,
    target_cover_weeks_eu_3pl_from_category text,
    target_cover_weeks_eu_fba_from_category text,
    target_cover_weeks_au_3pl_from_category text,
    target_cover_weeks_au_fba_from_category text,
    target_cover_weeks_ca_fba_from_category text,
    target_cover_weeks_uk_3pl text,
    target_cover_weeks_uk_fba text,
    target_cover_weeks_us_3pl text,
    target_cover_weeks_us_fba text,
    target_cover_weeks_eu_3pl text,
    target_cover_weeks_eu_fba text,
    target_cover_weeks_au_3pl text,
    target_cover_weeks_au_fba text,
    target_cover_weeks_ca_fba text,
    category_name_final text,
    subcategory_name_final text,
    categories_copy text,
    sku_barcode text,
    carton_barcode text,
    inner_barcode text,
    barcode_sku_name_final text,
    barcode_carton_name text,
    barcode_inner_name text,
    shp_swatch_final text,
    colour_swatch_url text,
    grs_material_product text,
    grs_approved text,
    grs_material_carton text,
    pallet_qty text,
    inventory_au_3pl text,
    inventory_us_awd text,
    inventory_uk_3pl text,
    inventory_eu_3pl text,
    inventory_us_3pl text,
    inventory_eu_fba text,
    inventory_uk_fba text,
    inventory_us_fba text,
    inventory_au_fba text,
    inventory_ca_fba text,
    size_short text,
    cogs_uk_3pl_final numeric,
    cogs_us_3pl_final numeric,
    cogs_eu_3pl_final numeric,
    cogs_au_3pl_final numeric,
    cogs_ca_3pl_final numeric
);


--
-- Name: sales_actuals; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.sales_actuals (
    sku text NOT NULL,
    country text NOT NULL,
    channel text NOT NULL,
    month date NOT NULL,
    units numeric DEFAULT 0 NOT NULL,
    revenue numeric DEFAULT 0 NOT NULL,
    source text DEFAULT 'airtable_backfill'::text NOT NULL,
    loaded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT sales_actuals_channel_check CHECK ((channel = ANY (ARRAY['DTC'::text, 'B2B'::text, 'FBA'::text]))),
    CONSTRAINT sales_actuals_country_check CHECK ((country = ANY (ARRAY['UK'::text, 'US'::text, 'EU'::text, 'AU'::text, 'CA'::text]))),
    CONSTRAINT sales_actuals_month_check CHECK ((EXTRACT(day FROM month) = (1)::numeric))
);


--
-- Name: category_sales_summary; Type: VIEW; Schema: planner; Owner: -
--

CREATE VIEW planner.category_sales_summary AS
 SELECT COALESCE(p.category, 'Unknown'::text) AS category,
    COALESCE(p.subcategory, 'Unknown'::text) AS subcategory,
    s.country,
    s.channel,
    s.month,
    (sum(s.units))::bigint AS units,
    round(sum(s.revenue), 2) AS revenue,
    count(DISTINCT s.sku) AS sku_count,
    bool_or(COALESCE((ce.subcategory IS NOT NULL), false)) AS is_excluded_category
   FROM ((planner.sales_actuals s
     LEFT JOIN planner.products p ON ((p.sku = s.sku)))
     LEFT JOIN planner.category_exclusions ce ON ((ce.subcategory = p.subcategory)))
  GROUP BY COALESCE(p.category, 'Unknown'::text), COALESCE(p.subcategory, 'Unknown'::text), s.country, s.channel, s.month;


--
-- Name: category_target_cover; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.category_target_cover (
    category text NOT NULL,
    warehouse text NOT NULL,
    target_cover_weeks numeric NOT NULL
);


--
-- Name: channel_map; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.channel_map (
    project_name text NOT NULL,
    country text,
    channel text,
    is_ignored boolean DEFAULT false NOT NULL,
    notes text
);


--
-- Name: contribution_targets; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.contribution_targets (
    category text NOT NULL,
    country text NOT NULL,
    channel text NOT NULL,
    market_tier text NOT NULL,
    target_contribution_pct numeric
);


--
-- Name: crossdock_shipments; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.crossdock_shipments (
    po text NOT NULL,
    sku text NOT NULL,
    qty numeric,
    submitted_by text,
    submitted_at timestamp with time zone DEFAULT now()
);


--
-- Name: demand_action_state; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.demand_action_state (
    action_key text NOT NULL,
    status text,
    snooze_until date,
    note text,
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: deposits; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.deposits (
    reference text,
    supplier_name text,
    supplier_id bigint,
    prod_no text,
    country text,
    description text,
    is_deposit boolean DEFAULT false NOT NULL,
    amount numeric(14,2),
    date_due date,
    date_likely_pay date,
    estimated_pay_date date,
    date_paid date,
    date_paid_link date,
    xero_fx numeric(12,5),
    deposit_used numeric(14,2),
    deposit_remaining numeric(14,2),
    production_contract text,
    linked_pos text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    id bigint NOT NULL,
    xero_account_code text,
    status text
);


--
-- Name: deposits_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.deposits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME planner.deposits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: duty_rates; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.duty_rates (
    id bigint NOT NULL,
    category text,
    country text,
    duty_pct numeric,
    notes text,
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: duty_rates_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.duty_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME planner.duty_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: etl_runs; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.etl_runs (
    id bigint NOT NULL,
    job text NOT NULL,
    status text NOT NULL,
    rows_affected integer,
    message text,
    ran_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: etl_runs_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.etl_runs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME planner.etl_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: financial_model; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.financial_model (
    fy text NOT NULL,
    category text NOT NULL,
    country text NOT NULL,
    quarter integer NOT NULL,
    growth_pct numeric,
    price_change_pct numeric,
    notes text,
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: flexport_shipments; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.flexport_shipments (
    flex_id text NOT NULL,
    shipment_name text,
    mode text,
    status_description text,
    incoterm text,
    freight_type text,
    freight_carriers text,
    mbl_number text,
    container_numbers text,
    cleared_customs_date date,
    ams_numbers text,
    planned_transit_time integer,
    actual_transit_time integer,
    total_quoted_amount numeric(14,2),
    origin_planned_departure date,
    origin_estimated_departure date,
    origin_actual_departure date,
    dep_port_planned_departure date,
    dep_port_estimated_departure date,
    dep_port_actual_departure date,
    arr_port_actual_arrival date,
    arr_port_estimated_arrival date,
    arr_port_planned_arrival date,
    dest_planned_arrival date,
    dest_estimated_arrival date,
    dest_actual_arrival date,
    shipments_ref text,
    packing_date date,
    departure_date date,
    landing_date date,
    arrival_date date,
    estimated_shipment_cost numeric(14,2),
    shipments_2 text,
    last_modified_time text,
    total_invoiced_amount numeric(14,2),
    customs_duty_cost numeric(14,2),
    total_freight_cost numeric(14,2),
    vat_costs numeric(14,2),
    quote_requested_date date
);


--
-- Name: forecast_inputs; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.forecast_inputs (
    subcategory text NOT NULL,
    country text NOT NULL,
    channel text NOT NULL,
    month date,
    value_raw text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    source text DEFAULT 'airtable_backfill'::text NOT NULL
);


--
-- Name: forecast_outputs; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.forecast_outputs (
    sku text NOT NULL,
    warehouse text NOT NULL,
    channel text NOT NULL,
    month date NOT NULL,
    units integer NOT NULL,
    source text DEFAULT 'airtable_backfill'::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: forecast_runs; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.forecast_runs (
    id bigint NOT NULL,
    run_at timestamp with time zone DEFAULT now() NOT NULL,
    engine_version text NOT NULL,
    horizon_start date NOT NULL,
    horizon_end date NOT NULL,
    notes text
);


--
-- Name: forecast_runs_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.forecast_runs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME planner.forecast_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forecasts; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.forecasts (
    run_id bigint NOT NULL,
    level text NOT NULL,
    subcategory text NOT NULL,
    country text NOT NULL,
    channel text NOT NULL,
    sku text NOT NULL,
    warehouse text NOT NULL,
    month date NOT NULL,
    units integer NOT NULL,
    method text,
    reason text,
    CONSTRAINT forecasts_level_check CHECK ((level = ANY (ARRAY['subcategory'::text, 'sku'::text])))
);


--
-- Name: freight_rates; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.freight_rates (
    id bigint NOT NULL,
    destination text,
    container_size text,
    cost numeric,
    currency text DEFAULT 'USD'::text,
    notes text,
    updated_at timestamp with time zone DEFAULT now(),
    pallets integer
);


--
-- Name: freight_rates_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.freight_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME planner.freight_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_tax_rates; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.import_tax_rates (
    country text NOT NULL,
    tax_pct numeric,
    base text DEFAULT 'landed'::text,
    notes text,
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: inbound_shipments; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.inbound_shipments (
    id bigint NOT NULL,
    reference text NOT NULL,
    sku text NOT NULL,
    source_type text,
    source_location text,
    destination_warehouse text,
    quantity integer DEFAULT 0 NOT NULL,
    received_quantity integer DEFAULT 0 NOT NULL,
    estimated_delivery_date date,
    status text,
    notes text,
    loaded_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: inbound_shipments_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.inbound_shipments ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME planner.inbound_shipments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_snapshots; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.inventory_snapshots (
    sku text NOT NULL,
    warehouse text NOT NULL,
    snapshot_date date NOT NULL,
    available integer NOT NULL
);


--
-- Name: key_account_forecasts; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.key_account_forecasts (
    client text NOT NULL,
    sku text NOT NULL,
    warehouse text,
    ship_date date NOT NULL,
    quantity integer NOT NULL,
    loaded_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: payment_fx; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.payment_fx (
    run_date date NOT NULL,
    supplier text NOT NULL,
    paid_currency text,
    paid_amount numeric,
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: payment_likely_dates; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.payment_likely_dates (
    line_key text NOT NULL,
    likely_date date,
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: payment_run_meta; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.payment_run_meta (
    run_date date NOT NULL,
    bank text,
    paid_currency text,
    bank_amount numeric(14,2),
    fx_rate numeric(12,5),
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: payment_runs; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.payment_runs (
    id bigint NOT NULL,
    invoice_reference text,
    payment_date date,
    supplier_name text,
    paid_from text,
    total_payment numeric(14,2),
    usd_amount numeric(14,2),
    gbp_amount numeric(14,2),
    eur_amount numeric(14,2),
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: payment_runs_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.payment_runs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME planner.payment_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_transactions; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.payment_transactions (
    id bigint NOT NULL,
    payment_date date,
    payment_run_ref text,
    transaction_reference text,
    transaction_type text,
    transaction_amount numeric(14,2),
    transaction_supplier text,
    invoice_reference text,
    deposit_ref text,
    po_completion text,
    po_balance_1 text,
    po_balance_2 text,
    po_balance_3 text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    paid_currency text,
    paid_amount numeric
);


--
-- Name: payment_transactions_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.payment_transactions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME planner.payment_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portal_additional_costs; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.portal_additional_costs (
    id bigint NOT NULL,
    po text NOT NULL,
    description text,
    qty numeric,
    price numeric,
    submitted_by text,
    submitted_at timestamp with time zone DEFAULT now()
);


--
-- Name: portal_additional_costs_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.portal_additional_costs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME planner.portal_additional_costs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portal_attachments; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.portal_attachments (
    id bigint NOT NULL,
    po text,
    supplier_id bigint,
    filename text,
    mime text,
    byte_size integer,
    data bytea,
    uploaded_by text,
    uploaded_at timestamp with time zone DEFAULT now()
);


--
-- Name: portal_attachments_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.portal_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME planner.portal_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portal_line_costs; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.portal_line_costs (
    po text NOT NULL,
    sku text NOT NULL,
    actual_cost numeric,
    submitted_by text,
    submitted_at timestamp with time zone DEFAULT now(),
    final_cost numeric,
    amended_qty numeric,
    is_added boolean DEFAULT false,
    confirmed_at timestamp with time zone
);


--
-- Name: portal_magic_tokens; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.portal_magic_tokens (
    token text NOT NULL,
    email text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone
);


--
-- Name: portal_sessions; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.portal_sessions (
    token text NOT NULL,
    email text NOT NULL,
    supplier_id bigint,
    created_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone NOT NULL
);


--
-- Name: preorders; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.preorders (
    reference text NOT NULL,
    sku text NOT NULL,
    warehouse text,
    ship_date date,
    quantity integer NOT NULL,
    loaded_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: prepack_bom; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.prepack_bom (
    prepack_sku text NOT NULL,
    component_sku text NOT NULL
);


--
-- Name: prod_numbers; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.prod_numbers (
    id bigint NOT NULL,
    prod_no text,
    status text,
    xero_account_code text,
    xero_account_name text,
    xero_account_id text
);


--
-- Name: prod_numbers_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.prod_numbers ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME planner.prod_numbers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_countries; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.product_countries (
    sku text NOT NULL,
    country text NOT NULL,
    launch_date_retail date,
    launch_date_wholesale date,
    discontinue_date date,
    duty_pct numeric
);


--
-- Name: product_inventory; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.product_inventory (
    sku text NOT NULL,
    warehouse text NOT NULL,
    available integer DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: product_target_cover_override; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.product_target_cover_override (
    sku text NOT NULL,
    warehouse text NOT NULL,
    target_cover_weeks numeric NOT NULL
);


--
-- Name: production_deposits; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.production_deposits (
    prod_no text NOT NULL,
    supplier_name text NOT NULL,
    deposit_ref text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: purchase_order_lines; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.purchase_order_lines (
    id bigint NOT NULL,
    po_sku text NOT NULL,
    po text NOT NULL,
    sku text NOT NULL,
    qty integer,
    carton_qty integer,
    partial_carton_approved boolean DEFAULT false NOT NULL,
    cost_price numeric(12,4),
    po_status text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    erp_qty integer,
    proposed_at timestamp with time zone,
    proposed_by text,
    erp_cost numeric
);


--
-- Name: purchase_order_lines_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.purchase_order_lines ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME planner.purchase_order_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_orders; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.purchase_orders (
    po text NOT NULL,
    supplier_name text,
    supplier_id bigint,
    status text,
    shipment_ref text,
    prod_no text,
    batch_id text,
    batch_date date,
    branch text,
    client text,
    deposit_ref text,
    erp_po text,
    notes text,
    ship_type text,
    ship_type_overide text,
    sea_lead_time_days integer,
    country_code text,
    first_release_window text,
    start_production date,
    end_production_overide date,
    days_production_overide integer,
    warehouse_complete_date date,
    landing_date_overide date,
    delivery_date_overide date,
    balance_due_date_overide date,
    supplier_ship_date date,
    supplier_invoice_total numeric(14,2),
    order_value_estimation numeric(14,2),
    deposit_fx_rate numeric(12,5),
    credit_fee_assigned numeric(14,2),
    pay_start_deposit_assigned numeric(14,2),
    pay_start_deposit_date date,
    pay_completion_assigned numeric(14,2),
    pay_completion_date date,
    pay_balance_1_amount numeric(14,2),
    pay_balance_1_date date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    flexport_reference text,
    start_deposit_pct_override numeric,
    completion_pct_override numeric,
    pay_balance_2_amount numeric,
    pay_balance_2_date date,
    container_size text,
    production_status text,
    production_confirmed_at timestamp with time zone,
    client_requirements text,
    sales_order_ref text,
    crossdock_skus text,
    client_po_ref text,
    dispatch_order_ref text,
    final_delivery_address text
);


--
-- Name: scenario_fin_overlay; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.scenario_fin_overlay (
    channel text NOT NULL,
    country text NOT NULL,
    growth_pct numeric,
    price_pct numeric,
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: sell_through_targets; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.sell_through_targets (
    category text NOT NULL,
    market text NOT NULL,
    target_pct numeric,
    updated_at timestamp with time zone DEFAULT now(),
    cover_weeks_target numeric
);


--
-- Name: shipments; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.shipments (
    shipment_ref text NOT NULL,
    master_po text,
    carrier text,
    carrier_ref text,
    departure_date date,
    landing_date date,
    delivery_date date,
    arrival_date date,
    status text,
    notes text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    mode text,
    cost_manual numeric,
    tracked_delivery_date date,
    tracked_source text,
    branch text,
    country_code text
);


--
-- Name: sku_exclusions; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.sku_exclusions (
    prefix text NOT NULL,
    notes text
);


--
-- Name: sku_labels; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.sku_labels (
    sku text NOT NULL,
    status text,
    size text,
    category text,
    subcategory text,
    main_supplier text,
    carton_qty integer,
    product_barcode text,
    carton_barcode text,
    inner_barcode text,
    barcode_sku_name text,
    barcode_carton_name text,
    barcode_inner_name text,
    swatch_url text,
    grs_material text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    pallet_qty integer,
    release_window text,
    uk_carton_l numeric,
    uk_carton_w numeric,
    uk_carton_h numeric,
    uk_carton_wt numeric,
    us_carton_l numeric,
    us_carton_w numeric,
    us_carton_h numeric,
    us_carton_wt numeric,
    size_short text,
    variant_type text
);


--
-- Name: subcategories; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.subcategories (
    subcategory text NOT NULL,
    category text,
    is_active boolean DEFAULT true NOT NULL,
    is_seasonal boolean DEFAULT false NOT NULL,
    "grouping" text[],
    description text,
    loaded_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: supplier_notes; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.supplier_notes (
    id bigint NOT NULL,
    po text,
    supplier_id bigint,
    author_email text,
    author_kind text DEFAULT 'supplier'::text,
    body text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    read_at timestamp with time zone
);


--
-- Name: supplier_notes_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.supplier_notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME planner.supplier_notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supplier_portal_users; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.supplier_portal_users (
    id bigint NOT NULL,
    email text NOT NULL,
    supplier_id bigint,
    supplier_name text,
    contact_name text,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: supplier_portal_users_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.supplier_portal_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME planner.supplier_portal_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supplier_submissions; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.supplier_submissions (
    id bigint NOT NULL,
    supplier_id bigint,
    po text,
    shipment_ref text,
    kind text NOT NULL,
    value text,
    attachment_id bigint,
    status text DEFAULT 'pending'::text NOT NULL,
    submitted_by text,
    submitted_at timestamp with time zone DEFAULT now(),
    applied_by text,
    applied_at timestamp with time zone,
    note text
);


--
-- Name: supplier_submissions_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.supplier_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME planner.supplier_submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suppliers; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.suppliers (
    id bigint NOT NULL,
    code text,
    name text NOT NULL,
    business_name text,
    kind text DEFAULT 'supplier'::text NOT NULL,
    default_currency text DEFAULT 'USD'::text NOT NULL,
    start_deposit_pct numeric(5,2),
    completion_pct numeric(5,2),
    balance_pct numeric(5,2),
    credit_days integer,
    credit_type text,
    credit_fee_on_balance_pct numeric(5,2),
    production_days integer,
    incoterm text,
    contact_name text,
    email text,
    phone text,
    address_1 text,
    address_2 text,
    city text,
    state text,
    country text,
    postcode text,
    active boolean DEFAULT true NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT suppliers_credit_type_check CHECK ((credit_type = ANY (ARRAY['on_shipment'::text, 'on_clearance'::text]))),
    CONSTRAINT suppliers_default_currency_check CHECK ((default_currency = ANY (ARRAY['USD'::text, 'GBP'::text, 'EUR'::text, 'AUD'::text, 'CAD'::text]))),
    CONSTRAINT suppliers_kind_check CHECK ((kind = ANY (ARRAY['supplier'::text, 'freight'::text, 'internal'::text, 'other'::text])))
);


--
-- Name: suppliers_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

ALTER TABLE planner.suppliers ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME planner.suppliers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supply_action_state; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.supply_action_state (
    action_key text NOT NULL,
    status text,
    snooze_until date,
    note text,
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: trading_calendar; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.trading_calendar (
    id bigint NOT NULL,
    event_date date,
    market text,
    event_type text,
    title text,
    notes text,
    updated_at timestamp with time zone DEFAULT now(),
    category text,
    uplift_pct numeric,
    sku_list text
);


--
-- Name: trading_calendar_id_seq; Type: SEQUENCE; Schema: planner; Owner: -
--

CREATE SEQUENCE planner.trading_calendar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trading_calendar_id_seq; Type: SEQUENCE OWNED BY; Schema: planner; Owner: -
--

ALTER SEQUENCE planner.trading_calendar_id_seq OWNED BY planner.trading_calendar.id;


--
-- Name: v_product_availability; Type: VIEW; Schema: planner; Owner: -
--

CREATE VIEW planner.v_product_availability AS
 WITH combos(country, channel) AS (
         VALUES ('UK'::text,'DTC'::text), ('UK'::text,'FBA'::text), ('UK'::text,'B2B'::text), ('US'::text,'DTC'::text), ('US'::text,'FBA'::text), ('US'::text,'B2B'::text), ('EU'::text,'DTC'::text), ('EU'::text,'FBA'::text), ('EU'::text,'B2B'::text), ('AU'::text,'DTC'::text), ('AU'::text,'FBA'::text), ('CA'::text,'FBA'::text)
        )
 SELECT p.sku,
    c.country,
    c.channel,
    ((
        CASE ((c.country || '|'::text) || c.channel)
            WHEN 'UK|DTC'::text THEN p.available_uk_dtc
            WHEN 'UK|FBA'::text THEN p.available_uk_fba
            WHEN 'UK|B2B'::text THEN p.available_uk_b2b
            WHEN 'US|DTC'::text THEN p.available_us_dtc
            WHEN 'US|FBA'::text THEN p.available_us_fba
            WHEN 'US|B2B'::text THEN p.available_us_b2b
            WHEN 'EU|DTC'::text THEN p.available_eu_dtc
            WHEN 'EU|FBA'::text THEN p.available_eu_fba
            WHEN 'EU|B2B'::text THEN p.available_eu_b2b
            WHEN 'AU|DTC'::text THEN p.available_au_dtc
            WHEN 'AU|FBA'::text THEN p.available_au_fba
            WHEN 'CA|FBA'::text THEN p.available_ca_fba
            ELSE NULL::boolean
        END IS TRUE) AND (NOT ((pc.discontinue_date IS NOT NULL) AND (pc.discontinue_date < CURRENT_DATE))) AND (NOT ((c.channel = 'B2B'::text) AND (pc.launch_date_wholesale IS NOT NULL) AND (pc.launch_date_wholesale > CURRENT_DATE))) AND (NOT ((c.channel = ANY (ARRAY['DTC'::text, 'FBA'::text])) AND (pc.launch_date_retail IS NOT NULL) AND (pc.launch_date_retail > CURRENT_DATE)))) AS is_available
   FROM ((planner.products p
     CROSS JOIN combos c)
     LEFT JOIN planner.product_countries pc ON (((pc.sku = p.sku) AND (lower(pc.country) = lower(c.country)))))
  WHERE p.in_planning_scope;


--
-- Name: v_purchase_order_lines; Type: VIEW; Schema: planner; Owner: -
--

CREATE VIEW planner.v_purchase_order_lines AS
 SELECT l.id,
    l.po_sku,
    l.po,
    l.sku,
    l.qty,
    sl.carton_qty,
    l.partial_carton_approved,
    l.cost_price,
    l.po_status,
        CASE
            WHEN ((sl.carton_qty IS NULL) OR (sl.carton_qty = 0)) THEN NULL::text
            WHEN ((l.qty % sl.carton_qty) = 0) THEN '✅ Full Cartons'::text
            WHEN l.partial_carton_approved THEN 'OK Partial'::text
            ELSE ('⚠️ Partial Carton - up to '::text || ((ceil(((l.qty)::numeric / (sl.carton_qty)::numeric)) * (sl.carton_qty)::numeric))::integer)
        END AS full_carton_check
   FROM (planner.purchase_order_lines l
     LEFT JOIN planner.sku_labels sl ON ((sl.sku = l.sku)));


--
-- Name: warehouse_config; Type: TABLE; Schema: planner; Owner: -
--

CREATE TABLE planner.warehouse_config (
    warehouse text NOT NULL,
    country text NOT NULL,
    warehouse_type text NOT NULL,
    transfer_from_3pl_weeks numeric,
    fba_transfer_min_units integer,
    CONSTRAINT warehouse_config_warehouse_type_check CHECK ((warehouse_type = ANY (ARRAY['3pl'::text, 'fba'::text])))
);


--
-- Name: trading_calendar id; Type: DEFAULT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.trading_calendar ALTER COLUMN id SET DEFAULT nextval('planner.trading_calendar_id_seq'::regclass);


--
-- Name: air_freight_rates air_freight_rates_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.air_freight_rates
    ADD CONSTRAINT air_freight_rates_pkey PRIMARY KEY (id);


--
-- Name: batches batches_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.batches
    ADD CONSTRAINT batches_pkey PRIMARY KEY (batch);


--
-- Name: bi_rules bi_rules_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.bi_rules
    ADD CONSTRAINT bi_rules_pkey PRIMARY KEY (id);


--
-- Name: branches branches_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.branches
    ADD CONSTRAINT branches_pkey PRIMARY KEY (name);


--
-- Name: buy_plan buy_plan_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.buy_plan
    ADD CONSTRAINT buy_plan_pkey PRIMARY KEY (id);


--
-- Name: buy_plan buy_plan_run_id_sku_warehouse_plan_type_order_month_key; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.buy_plan
    ADD CONSTRAINT buy_plan_run_id_sku_warehouse_plan_type_order_month_key UNIQUE (run_id, sku, warehouse, plan_type, order_month);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (category);


--
-- Name: category_exclusions category_exclusions_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.category_exclusions
    ADD CONSTRAINT category_exclusions_pkey PRIMARY KEY (subcategory);


--
-- Name: category_target_cover category_target_cover_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.category_target_cover
    ADD CONSTRAINT category_target_cover_pkey PRIMARY KEY (category, warehouse);


--
-- Name: channel_map channel_map_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.channel_map
    ADD CONSTRAINT channel_map_pkey PRIMARY KEY (project_name);


--
-- Name: contribution_targets contribution_targets_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.contribution_targets
    ADD CONSTRAINT contribution_targets_pkey PRIMARY KEY (category, country, channel, market_tier);


--
-- Name: crossdock_shipments crossdock_shipments_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.crossdock_shipments
    ADD CONSTRAINT crossdock_shipments_pkey PRIMARY KEY (po, sku);


--
-- Name: demand_action_state demand_action_state_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.demand_action_state
    ADD CONSTRAINT demand_action_state_pkey PRIMARY KEY (action_key);


--
-- Name: deposits deposits_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.deposits
    ADD CONSTRAINT deposits_pkey PRIMARY KEY (id);


--
-- Name: duty_rates duty_rates_category_country_key; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.duty_rates
    ADD CONSTRAINT duty_rates_category_country_key UNIQUE (category, country);


--
-- Name: duty_rates duty_rates_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.duty_rates
    ADD CONSTRAINT duty_rates_pkey PRIMARY KEY (id);


--
-- Name: etl_runs etl_runs_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.etl_runs
    ADD CONSTRAINT etl_runs_pkey PRIMARY KEY (id);


--
-- Name: financial_model financial_model_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.financial_model
    ADD CONSTRAINT financial_model_pkey PRIMARY KEY (fy, category, country, quarter);


--
-- Name: flexport_shipments flexport_shipments_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.flexport_shipments
    ADD CONSTRAINT flexport_shipments_pkey PRIMARY KEY (flex_id);


--
-- Name: forecast_inputs forecast_inputs_subcategory_country_channel_month_key; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.forecast_inputs
    ADD CONSTRAINT forecast_inputs_subcategory_country_channel_month_key UNIQUE NULLS NOT DISTINCT (subcategory, country, channel, month);


--
-- Name: forecast_outputs forecast_outputs_sku_wh_ch_month_key; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.forecast_outputs
    ADD CONSTRAINT forecast_outputs_sku_wh_ch_month_key UNIQUE NULLS NOT DISTINCT (sku, warehouse, channel, month);


--
-- Name: forecast_runs forecast_runs_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.forecast_runs
    ADD CONSTRAINT forecast_runs_pkey PRIMARY KEY (id);


--
-- Name: forecasts forecasts_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.forecasts
    ADD CONSTRAINT forecasts_pkey PRIMARY KEY (run_id, level, subcategory, country, channel, month, sku, warehouse);


--
-- Name: freight_rates freight_rates_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.freight_rates
    ADD CONSTRAINT freight_rates_pkey PRIMARY KEY (id);


--
-- Name: import_tax_rates import_tax_rates_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.import_tax_rates
    ADD CONSTRAINT import_tax_rates_pkey PRIMARY KEY (country);


--
-- Name: inbound_shipments inbound_shipments_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.inbound_shipments
    ADD CONSTRAINT inbound_shipments_pkey PRIMARY KEY (id);


--
-- Name: inventory_snapshots inventory_snapshots_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.inventory_snapshots
    ADD CONSTRAINT inventory_snapshots_pkey PRIMARY KEY (sku, warehouse, snapshot_date);


--
-- Name: key_account_forecasts key_account_forecasts_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.key_account_forecasts
    ADD CONSTRAINT key_account_forecasts_pkey PRIMARY KEY (client, sku, ship_date);


--
-- Name: payment_fx payment_fx_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.payment_fx
    ADD CONSTRAINT payment_fx_pkey PRIMARY KEY (run_date, supplier);


--
-- Name: payment_likely_dates payment_likely_dates_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.payment_likely_dates
    ADD CONSTRAINT payment_likely_dates_pkey PRIMARY KEY (line_key);


--
-- Name: payment_run_meta payment_run_meta_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.payment_run_meta
    ADD CONSTRAINT payment_run_meta_pkey PRIMARY KEY (run_date);


--
-- Name: payment_runs payment_runs_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.payment_runs
    ADD CONSTRAINT payment_runs_pkey PRIMARY KEY (id);


--
-- Name: payment_transactions payment_transactions_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.payment_transactions
    ADD CONSTRAINT payment_transactions_pkey PRIMARY KEY (id);


--
-- Name: portal_additional_costs portal_additional_costs_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.portal_additional_costs
    ADD CONSTRAINT portal_additional_costs_pkey PRIMARY KEY (id);


--
-- Name: portal_attachments portal_attachments_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.portal_attachments
    ADD CONSTRAINT portal_attachments_pkey PRIMARY KEY (id);


--
-- Name: portal_line_costs portal_line_costs_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.portal_line_costs
    ADD CONSTRAINT portal_line_costs_pkey PRIMARY KEY (po, sku);


--
-- Name: portal_magic_tokens portal_magic_tokens_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.portal_magic_tokens
    ADD CONSTRAINT portal_magic_tokens_pkey PRIMARY KEY (token);


--
-- Name: portal_sessions portal_sessions_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.portal_sessions
    ADD CONSTRAINT portal_sessions_pkey PRIMARY KEY (token);


--
-- Name: preorders preorders_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.preorders
    ADD CONSTRAINT preorders_pkey PRIMARY KEY (reference, sku);


--
-- Name: prepack_bom prepack_bom_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.prepack_bom
    ADD CONSTRAINT prepack_bom_pkey PRIMARY KEY (prepack_sku, component_sku);


--
-- Name: prod_numbers prod_numbers_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.prod_numbers
    ADD CONSTRAINT prod_numbers_pkey PRIMARY KEY (id);


--
-- Name: prod_numbers prod_numbers_prod_no_key; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.prod_numbers
    ADD CONSTRAINT prod_numbers_prod_no_key UNIQUE (prod_no);


--
-- Name: product_countries product_countries_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.product_countries
    ADD CONSTRAINT product_countries_pkey PRIMARY KEY (sku, country);


--
-- Name: product_inventory product_inventory_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.product_inventory
    ADD CONSTRAINT product_inventory_pkey PRIMARY KEY (sku, warehouse);


--
-- Name: product_target_cover_override product_target_cover_override_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.product_target_cover_override
    ADD CONSTRAINT product_target_cover_override_pkey PRIMARY KEY (sku, warehouse);


--
-- Name: production_deposits production_deposits_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.production_deposits
    ADD CONSTRAINT production_deposits_pkey PRIMARY KEY (prod_no, supplier_name, deposit_ref);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (sku);


--
-- Name: products products_sku_key; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.products
    ADD CONSTRAINT products_sku_key UNIQUE (sku);


--
-- Name: purchase_order_lines purchase_order_lines_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.purchase_order_lines
    ADD CONSTRAINT purchase_order_lines_pkey PRIMARY KEY (id);


--
-- Name: purchase_order_lines purchase_order_lines_po_sku_key; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.purchase_order_lines
    ADD CONSTRAINT purchase_order_lines_po_sku_key UNIQUE (po_sku);


--
-- Name: purchase_orders purchase_orders_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.purchase_orders
    ADD CONSTRAINT purchase_orders_pkey PRIMARY KEY (po);


--
-- Name: sales_actuals sales_actuals_key; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.sales_actuals
    ADD CONSTRAINT sales_actuals_key UNIQUE (sku, country, channel, month);


--
-- Name: sales_actuals sales_actuals_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.sales_actuals
    ADD CONSTRAINT sales_actuals_pkey PRIMARY KEY (sku, country, channel, month);


--
-- Name: scenario_fin_overlay scenario_fin_overlay_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.scenario_fin_overlay
    ADD CONSTRAINT scenario_fin_overlay_pkey PRIMARY KEY (channel, country);


--
-- Name: sell_through_targets sell_through_targets_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.sell_through_targets
    ADD CONSTRAINT sell_through_targets_pkey PRIMARY KEY (category, market);


--
-- Name: shipments shipments_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.shipments
    ADD CONSTRAINT shipments_pkey PRIMARY KEY (shipment_ref);


--
-- Name: sku_exclusions sku_exclusions_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.sku_exclusions
    ADD CONSTRAINT sku_exclusions_pkey PRIMARY KEY (prefix);


--
-- Name: sku_labels sku_labels_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.sku_labels
    ADD CONSTRAINT sku_labels_pkey PRIMARY KEY (sku);


--
-- Name: subcategories subcategories_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.subcategories
    ADD CONSTRAINT subcategories_pkey PRIMARY KEY (subcategory);


--
-- Name: supplier_notes supplier_notes_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.supplier_notes
    ADD CONSTRAINT supplier_notes_pkey PRIMARY KEY (id);


--
-- Name: supplier_portal_users supplier_portal_users_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.supplier_portal_users
    ADD CONSTRAINT supplier_portal_users_pkey PRIMARY KEY (id);


--
-- Name: supplier_submissions supplier_submissions_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.supplier_submissions
    ADD CONSTRAINT supplier_submissions_pkey PRIMARY KEY (id);


--
-- Name: suppliers suppliers_code_key; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.suppliers
    ADD CONSTRAINT suppliers_code_key UNIQUE (code);


--
-- Name: suppliers suppliers_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.suppliers
    ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);


--
-- Name: supply_action_state supply_action_state_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.supply_action_state
    ADD CONSTRAINT supply_action_state_pkey PRIMARY KEY (action_key);


--
-- Name: trading_calendar trading_calendar_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.trading_calendar
    ADD CONSTRAINT trading_calendar_pkey PRIMARY KEY (id);


--
-- Name: warehouse_config warehouse_config_pkey; Type: CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.warehouse_config
    ADD CONSTRAINT warehouse_config_pkey PRIMARY KEY (warehouse);


--
-- Name: deposits_reference_idx; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX deposits_reference_idx ON planner.deposits USING btree (reference);


--
-- Name: deposits_supplier_idx; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX deposits_supplier_idx ON planner.deposits USING btree (supplier_id);


--
-- Name: forecast_outputs_skuwhch_idx; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX forecast_outputs_skuwhch_idx ON planner.forecast_outputs USING btree (sku, warehouse, channel);


--
-- Name: idx_inbound_dest; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX idx_inbound_dest ON planner.inbound_shipments USING btree (destination_warehouse);


--
-- Name: idx_inbound_eta; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX idx_inbound_eta ON planner.inbound_shipments USING btree (estimated_delivery_date);


--
-- Name: idx_inbound_sku; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX idx_inbound_sku ON planner.inbound_shipments USING btree (sku);


--
-- Name: idx_sales_actuals_country_channel; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX idx_sales_actuals_country_channel ON planner.sales_actuals USING btree (country, channel);


--
-- Name: idx_sales_actuals_month; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX idx_sales_actuals_month ON planner.sales_actuals USING btree (month);


--
-- Name: pay_txn_deposit_idx; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX pay_txn_deposit_idx ON planner.payment_transactions USING btree (deposit_ref);


--
-- Name: pay_txn_type_idx; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX pay_txn_type_idx ON planner.payment_transactions USING btree (transaction_type);


--
-- Name: po_lines_po_idx; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX po_lines_po_idx ON planner.purchase_order_lines USING btree (po);


--
-- Name: po_lines_sku_idx; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX po_lines_sku_idx ON planner.purchase_order_lines USING btree (sku);


--
-- Name: portal_additional_costs_po_idx; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX portal_additional_costs_po_idx ON planner.portal_additional_costs USING btree (po);


--
-- Name: purchase_orders_prod_no_idx; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX purchase_orders_prod_no_idx ON planner.purchase_orders USING btree (prod_no);


--
-- Name: purchase_orders_status_idx; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX purchase_orders_status_idx ON planner.purchase_orders USING btree (status);


--
-- Name: purchase_orders_supplier_idx; Type: INDEX; Schema: planner; Owner: -
--

CREATE INDEX purchase_orders_supplier_idx ON planner.purchase_orders USING btree (supplier_id);


--
-- Name: supplier_portal_users_email_ux; Type: INDEX; Schema: planner; Owner: -
--

CREATE UNIQUE INDEX supplier_portal_users_email_ux ON planner.supplier_portal_users USING btree (lower(email));


--
-- Name: buy_plan buy_plan_run_id_fkey; Type: FK CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.buy_plan
    ADD CONSTRAINT buy_plan_run_id_fkey FOREIGN KEY (run_id) REFERENCES planner.forecast_runs(id);


--
-- Name: buy_plan buy_plan_warehouse_fkey; Type: FK CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.buy_plan
    ADD CONSTRAINT buy_plan_warehouse_fkey FOREIGN KEY (warehouse) REFERENCES planner.warehouse_config(warehouse);


--
-- Name: category_target_cover category_target_cover_warehouse_fkey; Type: FK CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.category_target_cover
    ADD CONSTRAINT category_target_cover_warehouse_fkey FOREIGN KEY (warehouse) REFERENCES planner.warehouse_config(warehouse);


--
-- Name: deposits deposits_supplier_id_fkey; Type: FK CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.deposits
    ADD CONSTRAINT deposits_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES planner.suppliers(id);


--
-- Name: forecasts forecasts_run_id_fkey; Type: FK CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.forecasts
    ADD CONSTRAINT forecasts_run_id_fkey FOREIGN KEY (run_id) REFERENCES planner.forecast_runs(id);


--
-- Name: inbound_shipments inbound_shipments_destination_warehouse_fkey; Type: FK CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.inbound_shipments
    ADD CONSTRAINT inbound_shipments_destination_warehouse_fkey FOREIGN KEY (destination_warehouse) REFERENCES planner.warehouse_config(warehouse);


--
-- Name: inventory_snapshots inventory_snapshots_warehouse_fkey; Type: FK CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.inventory_snapshots
    ADD CONSTRAINT inventory_snapshots_warehouse_fkey FOREIGN KEY (warehouse) REFERENCES planner.warehouse_config(warehouse);


--
-- Name: key_account_forecasts key_account_forecasts_warehouse_fkey; Type: FK CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.key_account_forecasts
    ADD CONSTRAINT key_account_forecasts_warehouse_fkey FOREIGN KEY (warehouse) REFERENCES planner.warehouse_config(warehouse);


--
-- Name: preorders preorders_warehouse_fkey; Type: FK CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.preorders
    ADD CONSTRAINT preorders_warehouse_fkey FOREIGN KEY (warehouse) REFERENCES planner.warehouse_config(warehouse);


--
-- Name: product_inventory product_inventory_warehouse_fkey; Type: FK CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.product_inventory
    ADD CONSTRAINT product_inventory_warehouse_fkey FOREIGN KEY (warehouse) REFERENCES planner.warehouse_config(warehouse);


--
-- Name: product_target_cover_override product_target_cover_override_warehouse_fkey; Type: FK CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.product_target_cover_override
    ADD CONSTRAINT product_target_cover_override_warehouse_fkey FOREIGN KEY (warehouse) REFERENCES planner.warehouse_config(warehouse);


--
-- Name: purchase_orders purchase_orders_supplier_id_fkey; Type: FK CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.purchase_orders
    ADD CONSTRAINT purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES planner.suppliers(id);


--
-- Name: subcategories subcategories_category_fkey; Type: FK CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.subcategories
    ADD CONSTRAINT subcategories_category_fkey FOREIGN KEY (category) REFERENCES planner.categories(category);


--
-- Name: supplier_portal_users supplier_portal_users_supplier_id_fkey; Type: FK CONSTRAINT; Schema: planner; Owner: -
--

ALTER TABLE ONLY planner.supplier_portal_users
    ADD CONSTRAINT supplier_portal_users_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES planner.suppliers(id);


--
-- Name: bi_rules; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.bi_rules ENABLE ROW LEVEL SECURITY;

--
-- Name: buy_plan; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.buy_plan ENABLE ROW LEVEL SECURITY;

--
-- Name: categories; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.categories ENABLE ROW LEVEL SECURITY;

--
-- Name: category_exclusions; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.category_exclusions ENABLE ROW LEVEL SECURITY;

--
-- Name: category_target_cover; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.category_target_cover ENABLE ROW LEVEL SECURITY;

--
-- Name: channel_map; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.channel_map ENABLE ROW LEVEL SECURITY;

--
-- Name: contribution_targets; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.contribution_targets ENABLE ROW LEVEL SECURITY;

--
-- Name: etl_runs; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.etl_runs ENABLE ROW LEVEL SECURITY;

--
-- Name: forecast_inputs; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.forecast_inputs ENABLE ROW LEVEL SECURITY;

--
-- Name: forecast_outputs; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.forecast_outputs ENABLE ROW LEVEL SECURITY;

--
-- Name: forecast_runs; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.forecast_runs ENABLE ROW LEVEL SECURITY;

--
-- Name: forecasts; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.forecasts ENABLE ROW LEVEL SECURITY;

--
-- Name: inbound_shipments; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.inbound_shipments ENABLE ROW LEVEL SECURITY;

--
-- Name: inventory_snapshots; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.inventory_snapshots ENABLE ROW LEVEL SECURITY;

--
-- Name: key_account_forecasts; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.key_account_forecasts ENABLE ROW LEVEL SECURITY;

--
-- Name: preorders; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.preorders ENABLE ROW LEVEL SECURITY;

--
-- Name: prepack_bom; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.prepack_bom ENABLE ROW LEVEL SECURITY;

--
-- Name: product_countries; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.product_countries ENABLE ROW LEVEL SECURITY;

--
-- Name: product_inventory; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.product_inventory ENABLE ROW LEVEL SECURITY;

--
-- Name: product_target_cover_override; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.product_target_cover_override ENABLE ROW LEVEL SECURITY;

--
-- Name: products; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.products ENABLE ROW LEVEL SECURITY;

--
-- Name: sales_actuals; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.sales_actuals ENABLE ROW LEVEL SECURITY;

--
-- Name: sku_exclusions; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.sku_exclusions ENABLE ROW LEVEL SECURITY;

--
-- Name: subcategories; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.subcategories ENABLE ROW LEVEL SECURITY;

--
-- Name: warehouse_config; Type: ROW SECURITY; Schema: planner; Owner: -
--

ALTER TABLE planner.warehouse_config ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--


