// Dock & Bay CLIENT PORTAL renderer (v28.008, Ben). Served at /client-view.js; the shell is supply/client.html.
// Direction approved 28-Sep-2026: "Showroom" look (image-led catalogue) + the "Workbench" stepped order flow with a side cart;
// the LINE SHEET has two views — table (default) and cards. Everything reads /api/cp/* (magic-link cookie session).
(function(){
  var esc=function(s){return String(s==null?'':s).replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});};
  var MON=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  function fd(s){ if(!s)return ''; var m=/^(\d{4})-(\d{2})-(\d{2})/.exec(String(s)); return m?(m[3]+'-'+MON[+m[2]-1]+'-'+m[1].slice(2)):String(s); }
  function money(n,cur){ n=Number(n)||0; var sym={GBP:'£',USD:'$',EUR:'€',AUD:'A$',CAD:'C$'}[cur||ME.client.currency]||''; return sym+n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}); }
  function units(n){ return (Number(n)||0).toLocaleString(); }
  var _toastT=null; function toast(msg,err){ var el=document.getElementById('cp-toast'); if(!el)return; el.textContent=msg; el.className=(err?'err ':'')+'on'; clearTimeout(_toastT); _toastT=setTimeout(function(){ el.className=''; },err?5000:2600); }
  function api(path,opts){ opts=opts||{}; var o={method:opts.method||'GET',headers:{}}; if(opts.body){ o.headers['content-type']='application/json'; o.body=JSON.stringify(opts.body); }
    return fetch(path,o).then(function(r){ if(r.status===401){ showLogin(); throw new Error('signed out'); } return r.json().then(function(j){ if(!r.ok||(j&&j.error&&!opts.allowError)){ var e=new Error((j&&j.error)||('HTTP '+r.status)); e.payload=j; throw e; } return j; }); }); }
  var root=document.getElementById('cp-root'), ME=null, CACHE={};
  // ── login ──
  function showLogin(msg){ ME=null; root.innerHTML='<div class="cp-login"><div class="cp-lcard"><div class="tiny mut" style="letter-spacing:.14em;text-transform:uppercase;font-weight:700">Dock &amp; Bay</div><h1>Client portal</h1><p>'+esc(msg||'Enter your email and we will send you a sign-in link.')+'</p>'
      +'<input id="cp-email" type="email" placeholder="you@company.com" autocomplete="email"><button class="cp-btn acc" id="cp-send" style="width:100%">Email me a link</button><div class="tiny mut" style="margin-top:12px">Links are valid for 7 days. No password needed.</div></div></div>';
    var b=document.getElementById('cp-send'), i=document.getElementById('cp-email');
    function go(){ var em=(i.value||'').trim(); if(!em||em.indexOf('@')<0){ toast('Enter a valid email',true); return; } b.disabled=true; b.textContent='Sending…'; fetch('/api/cp/request-link',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:em})}).then(function(){ b.textContent='Sent — check your inbox'; }).catch(function(){ b.disabled=false; b.textContent='Email me a link'; toast('Could not send, try again',true); }); }
    b.onclick=go; i.onkeydown=function(e){ if(e.key==='Enter')go(); }; i.focus(); }
  // ── shell ──
  var NAV=[['home','Home'],['catalogue','Catalogue'],['order','Order'],['orders','My orders'],['commission','Commission'],['messages','Messages']];
  function navItems(){ var f=ME.client.features; return NAV.filter(function(n){ if(n[0]==='order')return f.order_placement||f.sample_requests; if(n[0]==='catalogue')return f.view_line_sheet||f.view_stock; if(n[0]==='commission')return f.view_commission; if(n[0]==='messages')return f.messaging; return true; }); }
  function shell(){ var ini=(ME.user.name||ME.user.email||'?').split(/[\s@.]+/).filter(Boolean).slice(0,2).map(function(w){return w[0].toUpperCase();}).join('');
    root.innerHTML='<header class="cp-top"><a class="cp-brand" href="#/home">Dock &amp; Bay<small>Client portal</small></a><nav class="cp-nav" id="cp-nav">'+navItems().map(function(n){ return '<a class="cp-nl" data-t="'+n[0]+'" href="#/'+n[0]+'">'+n[1]+(n[0]==='messages'&&ME.unread?'<span class="cnt">'+ME.unread+'</span>':'')+'</a>'; }).join('')+'</nav>'
      +'<div class="cp-who"><b>'+esc(ME.client.name)+' · '+esc(typeLabel(ME.client.type))+'</b>'+esc(ME.user.name||ME.user.email)+' · '+esc(ME.client.market)+' · '+esc(ME.client.currency)+'</div><span class="cp-av" id="cp-av" title="Sign out">'+esc(ini)+'</span></header><main id="cp"></main>';
    document.getElementById('cp-av').onclick=function(){ if(confirm('Sign out of the client portal?')) fetch('/api/cp/logout',{method:'POST'}).then(function(){ showLogin('You have been signed out.'); }); }; }
  function typeLabel(t){ return {key_account:'key account',distributor:'distributor',agent:'agent group',direct_wholesale:'wholesale'}[t]||t; }
  function setActive(t){ document.querySelectorAll('#cp-nav .cp-nl').forEach(function(a){ a.classList.toggle('active',a.dataset.t===t); }); }
  function main(){ return document.getElementById('cp'); }
  function route(){ if(!ME)return; var seg=(location.hash||'').replace(/^#\/?/,'').split('/').filter(Boolean); var t=seg[0]||'home'; var allowed=navItems().map(function(n){return n[0];}); if(allowed.indexOf(t)<0)t='home'; setActive(t);
    ({home:vHome,catalogue:vCatalogue,order:vOrder,orders:vOrders,commission:vCommission,messages:vMessages})[t](seg.slice(1)); window.scrollTo(0,0); }
  window.addEventListener('hashchange',route);
  function boot(){ api('/api/cp/me').then(function(j){ ME=j; shell(); route(); }).catch(function(e){ if(e.message!=='signed out')showLogin(/expired/.test(location.search)?'That link has expired. Request a new one.':undefined); }); }
  // ── shared data ──
  function products(force){ if(CACHE.products&&!force)return Promise.resolve(CACHE.products); return api('/api/cp/line-sheet').then(function(j){ CACHE.products=j; return j; }); }
  function prices(){ if(CACHE.prices)return Promise.resolve(CACHE.prices); return api('/api/cp/prices').then(function(j){ CACHE.prices=j; return j; }); }
  function orders(){ return api('/api/cp/orders'); }
  function bandCls(b){ if(b==null)return ''; if(typeof b==='number')return b<20?'low':b<100?'mid':''; return b==='<20'?'low':(b==='20+'?'mid':''); }
  function stockTxt(p){ if(p.stock==null)return ''; return typeof p.stock==='number'?units(p.stock)+' in stock':p.stock; }
  function swatch(p){ return p.image?'':'<span class="sw" style="background:#9fb3c8"></span>'; }
  function seasonTag(p){ var t=[]; if(p.status==='PHASE OUT'||p.status==='LAST SEASON')t.push('<span class="tag disc">'+esc(p.status==='PHASE OUT'?'Phase out':'Last season')+'</span>'); else if(p.launch&&String(p.launch)>new Date().toISOString().slice(0,10))t.push('<span class="tag new">'+esc(p.season||'New')+' · '+fd(p.launch)+'</span>'); else t.push('<span class="tag">Active</span>'); return t.join(''); }
  function statusBadge(p){ if(p.status==='PHASE OUT')return '<span class="badge b-a">Phase out</span>'; if(p.status==='LAST SEASON')return '<span class="badge b-a">Last season</span>'; if(p.launch&&String(p.launch)>new Date().toISOString().slice(0,10))return '<span class="badge b-b">'+esc(p.season||'New')+' · '+fd(p.launch)+'</span>'; return '<span class="badge b-g">Active</span>'; }
  function dimsTxt(p){ var d=p.dims||{}; var c=d.carton||[]; if(c.every(function(x){return x==null;}))return ''; return c.map(function(x){return x==null?'–':x;}).join('×')+' '+d.unit; }
  // ── HOME ──
  function vHome(){ var m=main(); m.innerHTML='<div class="cp-lead">Loading…</div>';
    Promise.all([orders(),products().catch(function(){return null;})]).then(function(r){ var os=r[0].orders||[], ps=(r[1]&&r[1].products)||[];
      var open=os.filter(function(o){return o.bucket==='open'||o.bucket==='draft';}), drafts=os.filter(function(o){return o.bucket==='draft';}), unpaid=os.filter(function(o){return o.unpaid;}), ful=os.filter(function(o){return o.bucket==='fulfilled'&&o.fulfilled_date&&(Date.parse(new Date().toISOString().slice(0,10))-Date.parse(o.fulfilled_date))<30*86400000;});
      var newest=ps.filter(function(p){return p.launch&&String(p.launch)>new Date().toISOString().slice(0,7);}); var season=newest[0]&&newest[0].season; var heroImg=(newest.find(function(p){return p.image;})||ps.find(function(p){return p.image;})||{}).image;
      var f=ME.client.features; var hello=(ME.user.name||'').split(' ')[0];
      m.innerHTML=(f.view_line_sheet?'<div class="hero"><div><div class="eyebrow">'+(season?'New for '+esc(season):'Catalogue')+'</div><h1 class="cp-h">'+(season?esc(newest.length)+' new products landing '+fd(newest.map(function(p){return p.launch;}).sort()[0]):'Your live line sheet')+'</h1><p class="cp-lead">'+(season?'Reserve now and the order lands with our team as a draft for confirmation.':'Filter the catalogue and download exactly what you see.')+'</p><div class="cp-bar"><a class="cp-btn ink" href="#/catalogue'+(season?'?season='+encodeURIComponent(season):'')+'">Browse '+(season?esc(season):'catalogue')+'</a>'+((f.order_placement)?'<a class="cp-btn" href="#/order">Place an order</a>':'')+'</div></div><div class="ph"'+(heroImg?' style="background-image:url('+esc(heroImg)+')"':'')+'></div></div>':'')
        +'<h1 class="cp-h" style="font-size:22px">'+(hello?'Hello '+esc(hello):'Welcome')+'</h1><p class="cp-lead">'+esc(ME.client.name)+' · what needs your attention today.</p>'
        +'<div class="stat"><div><b>'+open.length+'</b><span>open orders'+(drafts.length?' · '+drafts.length+' awaiting confirmation':'')+'</span></div><div><b>'+ful.length+'</b><span>fulfilled in the last 30 days</span></div><div><b>'+money(unpaid.reduce(function(s,o){return s+(o.amount||0);},0))+'</b><span>unpaid · '+unpaid.filter(function(o){return o.days>30;}).length+' overdue</span></div>'+(f.view_stock?'<div><b>'+esc(ME.client.warehouse_label||'')+'</b><span>stock view'+(ME.client.stock_scope&&ME.client.stock_scope.mode==='custom'?' · custom report':'')+'</span></div>':'')+'</div>'
        +'<h3 style="margin:4px 0 8px">Recent orders</h3>'+(open.concat(os.filter(function(o){return o.bucket==='fulfilled';})).slice(0,6).map(orderRow).join('')||'<div class="cp-card mut">No orders yet.</div>')
        +(f.messaging&&ME.unread?'<div class="cp-card" style="border-color:var(--cp-acc)"><b>'+ME.unread+' new message'+(ME.unread===1?'':'s')+'</b> from Dock &amp; Bay · <a href="#/messages">open</a></div>':'');
    }).catch(function(e){ m.innerHTML='<div class="cp-card" style="color:var(--neg)">'+esc(e.message)+'</div>'; }); }
  function orderRow(o){ var st=o.bucket==='draft'?'<span class="badge b-b">'+(o.state==='submitted'?'Submitted · awaiting Ops':'Draft · with Ops')+'</span>':o.unpaid?'<span class="badge b-r">Unpaid'+(o.days>30?' · '+(o.days-30)+'d overdue':'')+'</span>':o.bucket==='fulfilled'?'<span class="badge b-g">'+(o.invoice_state==='paid'?'Paid':'Shipped '+fd(o.fulfilled_date))+'</span>':'<span class="badge b-n">'+esc(o.state||'open')+'</span>';
    return '<div class="orow"><div><div class="ref">'+esc(o.ref)+(o.sample?' <span class="badge b-a">Sample</span>':'')+'</div><div class="sub">'+esc(o.customer||o.company||'')+' · '+fd(o.created)+(o.customer_po?' · PO '+esc(o.customer_po):'')+'</div></div><div class="sub">'+(o.tracking?esc(o.carrier||'')+' '+esc(o.tracking):(o.requested?'requested '+fd(o.requested):(o.days!=null?o.days+' days old':'')))+'</div><div>'+st+'</div><div class="num">'+(o.sample?'non-invoiced':money(o.amount,o.currency))+'<div class="tiny mut">'+esc(o.document.label)+'</div></div><a class="cp-btn sm" href="#/orders/'+esc(o.id)+'">View</a></div>'; }
  // ── CATALOGUE (line sheet table/cards + stock) ──
  var CAT={view:'table',tab:'line',q:'',cat:'',colour:'',size:'',season:'',hideDisc:null};
  function vCatalogue(seg){ var m=main(); var f=ME.client.features; if(!f.view_line_sheet&&f.view_stock)CAT.tab='stock'; var qs=(location.hash.split('?')[1]||''); var qp={}; qs.split('&').forEach(function(kv){ var p=kv.split('='); if(p[0])qp[p[0]]=decodeURIComponent(p[1]||''); }); if(qp.season)CAT.season=qp.season; if(CAT.hideDisc==null)CAT.hideDisc=ME.hide_discontinued!==false;
    m.innerHTML='<h1 class="cp-h">'+(CAT.tab==='stock'?'Stock availability':'Line sheet')+'</h1><p class="cp-lead">Loading…</p>';
    products().then(function(d){ draw(d); }).catch(function(e){ m.innerHTML='<div class="cp-card" style="color:var(--neg)">'+esc(e.message)+'</div>'; });
    function draw(d){ var ps=d.products||[]; var cats=uniq(ps.map(function(p){return p.category;})), cols=uniq(ps.map(function(p){return p.colour;})), sizes=uniq(ps.map(function(p){return p.size;})), seasons=uniq(ps.map(function(p){return p.season;}));
      var list=ps.filter(function(p){ if(CAT.tab==='stock'&&p.stock==null)return false; if(CAT.hideDisc&&p.discontinued&&p.disc_date&&p.disc_date<new Date().toISOString().slice(0,10))return false; if(CAT.cat&&p.category!==CAT.cat)return false; if(CAT.colour&&p.colour!==CAT.colour)return false; if(CAT.size&&p.size!==CAT.size)return false; if(CAT.season&&p.season!==CAT.season)return false;
        if(CAT.q){ var q=CAT.q.toLowerCase(); if([p.sku,p.name,p.colour,p.parent,p.ean].join(' ').toLowerCase().indexOf(q)<0)return false; } return true; });
      var sel=function(id,val,opts,lbl){ return '<select class="cp-in" id="'+id+'"><option value="">'+lbl+': all</option>'+opts.map(function(o){return '<option'+(o===val?' selected':'')+'>'+esc(o)+'</option>';}).join('')+'</select>'; };
      m.innerHTML='<h1 class="cp-h">'+(CAT.tab==='stock'?'Stock availability':'Line sheet')+'</h1><p class="cp-lead">'+(CAT.tab==='stock'?'Stock for <b>'+esc(d.warehouse_label)+'</b>'+(d.stock_exact?' · exact units':' · shown in bands, not exact units')+(d.custom_sku_count?' · limited to the '+d.custom_sku_count+' SKUs on your report':''):'Live from our product master. '+esc(ME.client.market)+' dimensions and HS codes. Download exactly what you see as a PDF with images or an XLSX order form.')+'</p>'
        +'<div class="cp-bar">'+(f.view_line_sheet&&f.view_stock?'<span class="cp-seg"><span data-tab="line"'+(CAT.tab==='line'?' class="on"':'')+'>Line sheet</span><span data-tab="stock"'+(CAT.tab==='stock'?' class="on"':'')+'>Stock availability</span></span>':'')+(CAT.tab==='line'?'<span class="cp-seg" id="cp-view"><span data-v="table"'+(CAT.view==='table'?' class="on"':'')+'>▤ Table</span><span data-v="cards"'+(CAT.view==='cards'?' class="on"':'')+'>▦ Cards</span></span>':'')
        +'<input class="cp-in" id="cq" placeholder="Search SKU / product / colour" value="'+esc(CAT.q)+'" style="width:220px">'+sel('ccat',CAT.cat,cats,'Category')+sel('ccol',CAT.colour,cols,'Colour')+sel('csize',CAT.size,sizes,'Size')+sel('cseason',CAT.season,seasons,'Season')+'<label class="tiny"><input type="checkbox" id="chide"'+(CAT.hideDisc?' checked':'')+'> hide discontinued</label><span class="tiny mut" style="margin-left:auto">'+list.length+' of '+ps.length+'</span>'
        +(CAT.tab==='line'?'<button class="cp-btn" id="cpdf">⬇ PDF with images</button><button class="cp-btn" id="cxlsx">⬇ XLSX order form</button>':'<button class="cp-btn" id="cxlsx">⬇ XLSX</button>')+'</div>'
        +(CAT.tab==='stock'?stockTable(list,d):(CAT.view==='cards'?cards(list):lineTable(list,d)));
      m.querySelectorAll('.cp-seg [data-tab]').forEach(function(s){ s.onclick=function(){ CAT.tab=s.dataset.tab; draw(d); }; });
      m.querySelectorAll('#cp-view [data-v]').forEach(function(s){ s.onclick=function(){ CAT.view=s.dataset.v; draw(d); }; });
      var q=document.getElementById('cq'); q.oninput=function(){ CAT.q=q.value; var pos=q.selectionStart; draw(d); var q2=document.getElementById('cq'); q2.focus(); try{q2.setSelectionRange(pos,pos);}catch(e){} };
      [['ccat','cat'],['ccol','colour'],['csize','size'],['cseason','season']].forEach(function(x){ var el=document.getElementById(x[0]); el.onchange=function(){ CAT[x[1]]=el.value; draw(d); }; });
      document.getElementById('chide').onchange=function(){ CAT.hideDisc=this.checked; draw(d); };
      var pb=document.getElementById('cpdf'); if(pb)pb.onclick=function(){ pdfLineSheet(list,d); };
      document.getElementById('cxlsx').onclick=function(){ csvDownload(list,d,CAT.tab); };
      m.querySelectorAll('[data-add]').forEach(function(b){ b.onclick=function(){ cartAdd(b.dataset.add,Number(b.dataset.ctn)||1); toast('Added '+b.dataset.add+' to your order'); }; }); }
  }
  function uniq(a){ return Array.from(new Set(a.filter(Boolean))).sort(); }
  function lineTable(list,d){ var canOrder=ME.client.features.order_placement; var TH='<th></th><th>SKU</th><th>Product</th><th>Collection</th><th>Colour</th><th>Size</th><th>Season</th><th>Status</th><th>Disc. date</th><th class="num">Ctn qty</th><th>EAN</th><th>HS ('+esc(ME.client.market)+')</th><th class="num">Carton '+esc((d.products[0]||{dims:{}}).dims.unit||'cm')+'</th><th class="num">Ctn '+esc((d.products[0]||{dims:{}}).dims.wunit||'kg')+'</th><th>Material</th>'+(d.products.some(function(p){return p.stock!=null;})?'<th>Stock</th>':'')+(canOrder?'<th></th>':'');
    var byCat={}; list.forEach(function(p){ (byCat[p.category||'Other']=byCat[p.category||'Other']||[]).push(p); });
    var rows=Object.keys(byCat).map(function(c){ return '<tr><td colspan="20" class="cat">'+esc(c)+' <span class="mut" style="font-weight:400;text-transform:none;letter-spacing:0">· '+byCat[c].length+'</span></td></tr>'+byCat[c].map(function(p){ return '<tr><td><span class="imgcell"'+(p.image?' style="background-image:url('+esc(p.image)+')"':'')+'></span></td><td class="mono">'+esc(p.sku)+'</td><td style="white-space:normal;min-width:180px">'+esc(p.name)+'</td><td>'+esc(p.subcategory||'')+'</td><td>'+swatch(p)+esc(p.colour||'')+'</td><td>'+esc(p.size||'')+'</td><td>'+esc(p.season||'')+'</td><td>'+statusBadge(p)+'</td><td>'+(p.disc_date?fd(p.disc_date)+' <span class="tiny mut">('+esc(p.disc_basis)+')</span>':'<span class="faint">—</span>')+'</td><td class="num">'+(p.carton_qty==null?'':p.carton_qty)+'</td><td class="mono">'+esc(p.ean||'')+'</td><td class="mono">'+esc(p.hs||'')+'</td><td class="num">'+esc(dimsTxt(p))+'</td><td class="num">'+(p.dims.carton_weight==null?'':p.dims.carton_weight)+'</td><td>'+esc(p.material||'')+'</td>'+(d.products.some(function(x){return x.stock!=null;})?'<td>'+(p.stock!=null?'<span class="band '+bandCls(p.stock)+'">'+esc(stockTxt(p))+'</span>':'')+'</td>':'')+(canOrder?'<td><button class="cp-btn sm" data-add="'+esc(p.sku)+'" data-ctn="'+(p.carton_qty||1)+'">+ Add</button></td>':'')+'</tr>'; }).join(''); }).join('');
    return '<div class="cp-card flush"><div class="tw" style="max-height:70vh"><table class="cp"><thead><tr>'+TH+'</tr></thead><tbody>'+(rows||'<tr><td colspan="20" class="mut" style="padding:16px">Nothing matches.</td></tr>')+'</tbody></table></div></div>'; }
  function cards(list){ var canOrder=ME.client.features.order_placement; return '<div class="grid">'+list.map(function(p){ return '<div class="pc"><div class="ph"'+(p.image?' style="background-image:url('+esc(p.image)+')"':'')+'>'+seasonTag(p)+'</div><div class="bd"><div class="nm">'+esc(p.name)+'</div><div class="sku">'+esc(p.sku)+' · '+esc(p.size||'')+'</div><div class="meta">'+swatch(p)+esc(p.colour||'')+(p.subcategory?' · '+esc(p.subcategory):'')+(p.carton_qty?' · '+p.carton_qty+'/ctn':'')+(p.hs?' · HS '+esc(p.hs):'')+'</div>'+(p.disc_date?'<div class="meta">discontinues '+fd(p.disc_date)+' ('+esc(p.disc_basis)+')</div>':'')+'<div class="ft">'+(p.stock!=null?'<span class="band '+bandCls(p.stock)+'">'+esc(stockTxt(p))+'</span>':'<span></span>')+(canOrder?'<button class="cp-btn sm" data-add="'+esc(p.sku)+'" data-ctn="'+(p.carton_qty||1)+'">+ Add</button>':'')+'</div></div></div>'; }).join('')+'</div>'+(list.length?'':'<div class="cp-card mut">Nothing matches.</div>'); }
  function stockTable(list,d){ return '<div class="cp-card flush"><div class="tw" style="max-height:70vh"><table class="cp"><thead><tr><th>SKU</th><th>Product</th><th>Colour</th><th>Size</th><th>Season</th><th>Status</th><th>'+esc(d.warehouse_label)+'</th></tr></thead><tbody>'+list.map(function(p){ return '<tr><td class="mono">'+esc(p.sku)+'</td><td style="white-space:normal;min-width:180px">'+esc(p.name)+'</td><td>'+swatch(p)+esc(p.colour||'')+'</td><td>'+esc(p.size||'')+'</td><td>'+esc(p.season||'')+'</td><td>'+statusBadge(p)+'</td><td><span class="band '+bandCls(p.stock)+'">'+esc(stockTxt(p))+'</span></td></tr>'; }).join('')+'</tbody></table></div></div>'; }
  function csvDownload(list,d,tab){ var cols=tab==='stock'?['sku','name','colour','size','season','status','stock']:['sku','name','category','subcategory','colour','size','season','status','disc_date','ean','asin','carton_qty','inner_qty','hs','material','carton_dims','carton_weight','stock','qty'];
    var rows=[cols.map(function(c){return c==='qty'?'order qty':c;}).join(',')].concat(list.map(function(p){ return cols.map(function(c){ var v=c==='carton_dims'?dimsTxt(p):c==='qty'?'':p[c]; v=v==null?'':String(v); return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v; }).join(','); }));
    var blob=new Blob([rows.join('\n')],{type:'text/csv;charset=utf-8'}), u=URL.createObjectURL(blob), a=document.createElement('a'); a.href=u; a.download=(tab==='stock'?'stock-':'line-sheet-')+ME.client.market+'-'+new Date().toISOString().slice(0,10)+'.csv'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(function(){URL.revokeObjectURL(u);},1000); }
  function pdfLineSheet(list,d){ var w=window.open('','_blank'); if(!w){ toast('Allow pop-ups to print the line sheet',true); return; }
    w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Dock &amp; Bay line sheet · '+esc(ME.client.market)+'</title><style>body{font-family:system-ui,sans-serif;font-size:11px;color:#111;margin:18mm 14mm}h1{font-size:18px;margin:0 0 2px}.sub{color:#666;margin-bottom:12px}.g{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.c{border:1px solid #ddd;border-radius:6px;overflow:hidden;break-inside:avoid}.c .ph{aspect-ratio:4/3;background:#eee center/cover no-repeat}.c .b{padding:6px 8px}.nm{font-weight:700}.m{color:#666;font-size:10px}@media print{@page{margin:12mm}}</style></head><body><h1>Dock &amp; Bay · Line sheet</h1><div class="sub">'+esc(ME.client.name)+' · '+esc(ME.client.market)+' · '+list.length+' products · '+new Date().toISOString().slice(0,10)+'</div><div class="g">'+list.map(function(p){ return '<div class="c"><div class="ph"'+(p.image?' style="background-image:url('+esc(p.image)+')"':'')+'></div><div class="b"><div class="nm">'+esc(p.name)+'</div><div class="m">'+esc(p.sku)+' · '+esc(p.colour||'')+' · '+esc(p.size||'')+'</div><div class="m">'+(p.carton_qty?p.carton_qty+'/ctn · ':'')+(p.ean?'EAN '+esc(p.ean)+' · ':'')+(p.hs?'HS '+esc(p.hs):'')+'</div>'+(p.disc_date?'<div class="m">discontinues '+fd(p.disc_date)+'</div>':'')+'</div></div>'; }).join('')+'</div><script>setTimeout(function(){window.print();},400);<\/script></body></html>'); w.document.close(); }
  // ── ORDER (Workbench stepped flow + side cart) ──
  var ORD={step:1,type:'standard',browse:'category',q:'',season:'',cart:{},ship_to:{},customer_po:'',requested:'',method:'',notes:'',result:null};
  function cartAdd(sku,ctn){ ORD.cart[sku]=(ORD.cart[sku]||0)+ctn; saveCart(); }
  function saveCart(){ try{ localStorage.setItem('cpCart',JSON.stringify(ORD.cart)); }catch(e){} }
  try{ ORD.cart=JSON.parse(localStorage.getItem('cpCart')||'{}')||{}; }catch(e){}
  function vOrder(){ var m=main(); var f=ME.client.features; if(!f.order_placement&&f.sample_requests)ORD.type='sample'; m.innerHTML='<h1 class="cp-h">'+(ORD.type==='sample'?'Sample request':'New order')+'</h1><p class="cp-lead">Loading…</p>';
    Promise.all([products(),prices()]).then(function(r){ draw(r[0],r[1]); }).catch(function(e){ m.innerHTML='<div class="cp-card" style="color:var(--neg)">'+esc(e.message)+'</div>'; });
    function draw(d,pr){ var ps=d.products||[], P=pr.prices||{}, cur=pr.currency||ME.client.currency, byS={}; ps.forEach(function(p){ byS[p.sku]=p; });
      var lines=Object.keys(ORD.cart).filter(function(s){return ORD.cart[s]>0;}).map(function(s){ var p=byS[s]||{sku:s,name:s}; var q=ORD.cart[s], cq=Number(p.carton_qty)||0, partial=cq>0&&q%cq!==0, price=P[s]; return {sku:s,p:p,qty:q,cartons:cq?Math.round(q/cq*100)/100:null,partial:partial,price:price,amount:price!=null?price*q:null,disc:p.discontinued&&p.disc_date&&p.disc_date<new Date().toISOString().slice(0,10)}; });
      var unitsT=lines.reduce(function(s,l){return s+l.qty;},0), total=lines.reduce(function(s,l){return s+(l.amount||0);},0), partials=lines.filter(function(l){return l.partial;}).length, priced=lines.every(function(l){return l.price!=null;});
      if(ORD.result){ m.innerHTML='<h1 class="cp-h">Thank you</h1><p class="cp-lead">Your '+(ORD.result.type==='sample'?'sample request':'order')+' <b>#'+ORD.result.id+'</b> has been received.</p><div class="cp-card"><div class="kv"><b>Status</b><span>'+(ORD.result.status==='fulfil_draft'?'Draft <b>'+esc(ORD.result.fulfil.number||'')+'</b> is with our team for confirmation.':'Submitted — our team will confirm it shortly.')+'</span><b>Units</b><span>'+units(ORD.result.units)+'</span>'+(ORD.result.type==='sample'?'':'<b>Total</b><span>'+money(ORD.result.total,cur)+' ex shipping</span>')+'</div><div class="cp-bar" style="margin-top:12px"><a class="cp-btn acc" href="#/orders">My orders</a><button class="cp-btn" id="onew">Start another</button></div></div>'; document.getElementById('onew').onclick=function(){ ORD.result=null; ORD.step=1; draw(d,pr); }; return; }
      var steps='<div class="steps"><div data-s="1" class="'+(ORD.step===1?'on':'done')+'"><i>1</i>Lines</div><div data-s="2" class="'+(ORD.step===2?'on':ORD.step>2?'done':'')+'"><i>2</i>Delivery</div><div data-s="3" class="'+(ORD.step===3?'on':'')+'"><i>3</i>Review &amp; submit</div></div>';
      var typeSeg=(f.order_placement&&f.sample_requests)?'<span class="cp-seg" id="otype"><span data-t="standard"'+(ORD.type==='standard'?' class="on"':'')+'>Standard order</span><span data-t="sample"'+(ORD.type==='sample'?' class="on"':'')+'>Sample request</span></span>':'';
      var cart='<div class="cp-card cart"><h3>'+(ORD.type==='sample'?'Sample request':'Cart')+' <span class="mut tiny">· '+lines.length+' line'+(lines.length===1?'':'s')+' · '+units(unitsT)+' units</span></h3>'+(lines.length?lines.map(function(l){ return '<div class="row"><span class="mono">'+esc(l.sku)+' ×'+l.qty+(l.partial?' <span class="warn">⚠</span>':'')+'</span><span class="num">'+(ORD.type==='sample'?'':(l.amount!=null?money(l.amount,cur):'<span class="faint">price on request</span>'))+'</span></div>'; }).join(''):'<div class="mut tiny">Nothing added yet.</div>')
        +(ORD.type==='sample'?'<div class="row tot"><span>Non-invoiced samples</span><span></span></div>':'<div class="row tot"><span>Total ex shipping</span><span class="num">'+(priced?money(total,cur):money(total,cur)+' + POR')+'</span></div>')
        +(partials?'<div class="warn" style="margin:8px 0 4px">'+partials+' line'+(partials===1?'':'s')+' not whole cartons</div>':'')
        +'<div style="margin-top:10px">'+(ORD.step===1?'<button class="cp-btn acc" id="onext" style="width:100%"'+(lines.length?'':' disabled')+'>Continue to delivery →</button>':ORD.step===2?'<button class="cp-btn acc" id="onext" style="width:100%">Review order →</button>':'<button class="cp-btn acc" id="osubmit" style="width:100%">'+(ORD.type==='sample'?'Send sample request':'Submit order to Dock & Bay')+'</button>')+'</div>'+(lines.length?'<div style="margin-top:6px"><a class="tiny mut" id="oclear" style="cursor:pointer">clear all</a></div>':'')+'</div>';
      var body='';
      if(ORD.step===1){ var seasons=uniq(ps.map(function(p){return p.season;}));
        var list=ps.filter(function(p){ if(p.discontinued&&p.disc_date&&p.disc_date<new Date().toISOString().slice(0,10))return false; if(ORD.season&&p.season!==ORD.season)return false; if(ORD.q){ var q=ORD.q.toLowerCase(); if([p.sku,p.name,p.colour,p.parent].join(' ').toLowerCase().indexOf(q)<0)return false; } return true; });
        var showStock=ps.some(function(p){return p.stock!=null;})&&ME.client.type!=='distributor'; var ctl='<div class="cp-bar">'+typeSeg+'<span class="cp-seg" id="obrowse"><span data-b="category"'+(ORD.browse==='category'?' class="on"':'')+'>By category</span><span data-b="all"'+(ORD.browse==='all'?' class="on"':'')+'>All SKUs</span></span><input class="cp-in" id="oq" placeholder="search SKU / product" value="'+esc(ORD.q)+'" style="width:200px"><select class="cp-in" id="oseason"><option value="">Season: all</option>'+seasons.map(function(s){return '<option'+(s===ORD.season?' selected':'')+'>'+esc(s)+'</option>';}).join('')+'</select><span class="tiny mut" style="margin-left:auto">'+list.length+' products</span><button class="cp-btn" id="ocsv">⬆ Upload CSV</button><button class="cp-btn" id="otpl">⬇ Template</button></div>';
        var row=function(p){ var q=ORD.cart[p.sku]||''; var cq=Number(p.carton_qty)||0; var partial=q&&cq&&q%cq!==0; var price=P[p.sku];
          return '<tr><td><span class="imgcell"'+(p.image?' style="background-image:url('+esc(p.image)+')"':'')+'></span></td><td class="mono">'+esc(p.sku)+(ORD.browse==='all'?'<div class="tiny mut">'+esc(p.category||'')+'</div>':'')+'</td><td style="white-space:normal;min-width:160px">'+esc(p.name)+'</td><td>'+swatch(p)+esc(p.colour||'')+' · '+esc(p.size||'')+'</td><td>'+esc(p.season||'')+'</td><td>'+(p.disc_date?fd(p.disc_date)+' <span class="tiny mut">'+esc(p.disc_basis)+'</span>':'<span class="faint">—</span>')+'</td><td class="num">'+(cq||'')+'</td>'+(showStock?'<td class="num">'+(p.stock!=null?(typeof p.stock==='number'?units(p.stock):esc(p.stock)):'')+'</td>':'')+'<td class="num">'+(ORD.type==='sample'?'—':(price!=null?money(price,cur):'<span class="faint">POR</span>'))+'</td><td class="num"><input class="qty oq" data-sku="'+esc(p.sku)+'" value="'+esc(q)+'" inputmode="numeric"></td><td>'+(q?(partial?'<span class="warn">⚠ '+(Math.round(q/cq*10)/10)+' ctn · use '+(Math.floor(q/cq)*cq||cq)+' or '+(Math.ceil(q/cq)*cq)+'</span>':cq?'<span class="ok">'+(q/cq)+' ctn ✓</span>':''):'')+'</td></tr>'; };
        var TH='<tr><th></th><th>SKU</th><th>Product</th><th>Colour · size</th><th>Season</th><th>Disc.</th><th class="num">Units/ctn</th>'+(showStock?'<th class="num">Stock</th>':'')+'<th class="num">Price</th><th class="num">Qty</th><th>Cartons</th></tr>';
        var tb; if(ORD.browse==='category'){ var byCat={}; list.forEach(function(p){ (byCat[p.category||'Other']=byCat[p.category||'Other']||[]).push(p); }); tb=Object.keys(byCat).map(function(c){ return '<tr><td colspan="12" class="cat">'+esc(c)+'</td></tr>'+byCat[c].map(row).join(''); }).join(''); } else tb=list.map(row).join('');
        body=ctl+'<div class="three"><div class="cp-card flush"><div class="tw" style="max-height:68vh"><table class="cp"><thead>'+TH+'</thead><tbody>'+tb+'</tbody></table></div>'+(ME.client.type==='distributor'?'<div class="tiny mut" style="padding:8px 12px">Stock is not shown in order entry for distributor accounts.</div>':'')+'</div>'+cart+'</div>';
      } else if(ORD.step===2){ var st=ORD.ship_to;
        body=steps+'<div class="three"><div><div class="cp-card"><h3>Deliver to</h3><div class="kv"><b>Company</b><input class="cp-in st" data-f="company" value="'+esc(st.company||ME.client.name)+'"><b>Contact</b><input class="cp-in st" data-f="contact" value="'+esc(st.contact||ME.user.name||'')+'"><b>Address</b><textarea class="cp-in st" data-f="address" rows="3" style="height:auto;padding:8px 12px">'+esc(st.address||'')+'</textarea><b>Phone</b><input class="cp-in st" data-f="phone" value="'+esc(st.phone||'')+'"><b>Email</b><input class="cp-in st" data-f="email" value="'+esc(st.email||ME.user.email)+'"></div></div>'
          +'<div class="cp-card"><h3>Order details</h3><div class="kv"><b>Your PO #</b><input class="cp-in" id="opo" value="'+esc(ORD.customer_po)+'"><b>Requested delivery</b><input class="cp-in" id="oreq" type="date" value="'+esc(ORD.requested)+'"><b>Ship from</b><span class="tiny">'+esc(ME.client.warehouse_label||'')+'</span><b>Method</b><input class="cp-in" id="omethod" value="'+esc(ORD.method||ME.default_method||'')+'"><b>Notes</b><textarea class="cp-in" id="onotes" rows="2" style="height:auto;padding:8px 12px">'+esc(ORD.notes)+'</textarea></div></div><button class="cp-btn" id="oback">← Back to lines</button></div>'+cart+'</div>';
      } else { var probs=lines.filter(function(l){return l.disc;});
        body=steps+'<div class="three"><div><div class="cp-card flush"><div class="tw"><table class="cp"><thead><tr><th>SKU</th><th>Product</th><th class="num">Qty</th><th class="num">Cartons</th><th class="num">Price</th><th class="num">Amount</th><th></th></tr></thead><tbody>'+lines.map(function(l){ return '<tr><td class="mono">'+esc(l.sku)+'</td><td style="white-space:normal">'+esc(l.p.name||'')+'</td><td class="num">'+l.qty+'</td><td class="num">'+(l.cartons==null?'':l.cartons)+'</td><td class="num">'+(ORD.type==='sample'?'—':(l.price!=null?money(l.price,cur):'POR'))+'</td><td class="num">'+(ORD.type==='sample'?'—':(l.amount!=null?money(l.amount,cur):''))+'</td><td>'+(l.partial?'<span class="warn">⚠ partial carton</span>':'')+(l.disc?' <span class="badge b-r">discontinued</span>':'')+'</td></tr>'; }).join('')+'</tbody></table></div></div>'
          +'<div class="cp-card"><h3>Delivery</h3><div class="kv"><b>Deliver to</b><span>'+esc(ORD.ship_to.company||'')+(ORD.ship_to.contact?' · '+esc(ORD.ship_to.contact):'')+'<div class="tiny mut" style="white-space:pre-wrap">'+esc(ORD.ship_to.address||'')+'</div></span><b>Your PO #</b><span>'+esc(ORD.customer_po||'—')+'</span><b>Requested</b><span>'+(ORD.requested?fd(ORD.requested):'—')+'</span><b>Ship from</b><span>'+esc(ME.client.warehouse_label||'')+'</span><b>Method</b><span>'+esc(ORD.method||'—')+'</span></div></div>'
          +(partials?'<div class="cp-card" style="border-color:var(--amber)"><b class="warn">'+partials+' line'+(partials===1?' is':'s are')+' not whole cartons.</b> <span class="tiny">Go back and round the quantity, or tick to submit as is (our team will round up).</span><div><label class="tiny"><input type="checkbox" id="oaccept"> submit anyway</label></div></div>':'')
          +(probs.length?'<div class="cp-card" style="border-color:var(--neg)"><b style="color:var(--neg)">'+probs.length+' discontinued SKU'+(probs.length===1?'':'s')+'</b> — remove '+probs.map(function(l){return esc(l.sku);}).join(', ')+' before submitting.</div>':'')
          +'<div class="tiny mut">On submit the order lands with Dock &amp; Bay as a draft for confirmation. You will get an email record; our team is notified straight away.</div><div style="margin-top:8px"><button class="cp-btn" id="oback">← Back</button></div></div>'+cart+'</div>'; }
      m.innerHTML='<h1 class="cp-h">'+(ORD.type==='sample'?'Sample request':'New order')+'</h1><p class="cp-lead">'+(ORD.type==='sample'?'A small, non-invoiced quantity for evaluation. Same form, no prices.':'Whole cartons only; partial quantities are flagged as you type. The order lands with our team as a draft and you receive a confirmation.')+'</p>'+(ORD.step===1?steps:'')+body;
      m.querySelectorAll('.steps [data-s]').forEach(function(s){ s.onclick=function(){ var n=+s.dataset.s; if(n<ORD.step||(n===2&&lines.length)){ ORD.step=n; draw(d,pr); } }; });
      var ot=document.getElementById('otype'); if(ot)ot.querySelectorAll('[data-t]').forEach(function(s){ s.onclick=function(){ ORD.type=s.dataset.t; draw(d,pr); }; });
      var ob=document.getElementById('obrowse'); if(ob)ob.querySelectorAll('[data-b]').forEach(function(s){ s.onclick=function(){ ORD.browse=s.dataset.b; draw(d,pr); }; });
      var oq=document.getElementById('oq'); if(oq)oq.oninput=function(){ ORD.q=oq.value; var pos=oq.selectionStart; draw(d,pr); var q2=document.getElementById('oq'); q2.focus(); try{q2.setSelectionRange(pos,pos);}catch(e){} };
      var os=document.getElementById('oseason'); if(os)os.onchange=function(){ ORD.season=os.value; draw(d,pr); };
      m.querySelectorAll('input.oq').forEach(function(inp){ inp.onchange=function(){ var v=Math.max(0,Math.round(Number(inp.value)||0)); if(v)ORD.cart[inp.dataset.sku]=v; else delete ORD.cart[inp.dataset.sku]; saveCart(); var active=document.activeElement; draw(d,pr); }; });
      var oc=document.getElementById('oclear'); if(oc)oc.onclick=function(){ if(confirm('Clear the whole cart?')){ ORD.cart={}; saveCart(); draw(d,pr); } };
      m.querySelectorAll('.st').forEach(function(inp){ inp.onchange=function(){ ORD.ship_to[inp.dataset.f]=inp.value; }; });
      ['opo','oreq','omethod','onotes'].forEach(function(id){ var el=document.getElementById(id); if(el)el.onchange=function(){ ORD[{opo:'customer_po',oreq:'requested',omethod:'method',onotes:'notes'}[id]]=el.value; }; });
      var nx=document.getElementById('onext'); if(nx)nx.onclick=function(){ if(ORD.step===2){ if(!ORD.ship_to.company)ORD.ship_to.company=ME.client.name; } ORD.step++; draw(d,pr); };
      var bk=document.getElementById('oback'); if(bk)bk.onclick=function(){ ORD.step--; draw(d,pr); };
      var sb=document.getElementById('osubmit'); if(sb)sb.onclick=function(){ var acc=document.getElementById('oaccept'); if(partials&&!(acc&&acc.checked)){ toast('Round the partial cartons or tick "submit anyway"',true); return; } if(probs.length){ toast('Remove the discontinued SKUs first',true); return; }
        sb.disabled=true; sb.textContent='Submitting…';
        api('/api/cp/order',{method:'POST',body:{order_type:ORD.type,lines:lines.map(function(l){return {sku:l.sku,qty:l.qty};}),ship_to:ORD.ship_to,customer_po:ORD.customer_po,requested_date:ORD.requested||null,method:ORD.method,notes:ORD.notes,accept_partial:true}}).then(function(j){ ORD.result=Object.assign({type:ORD.type},j); ORD.cart={}; saveCart(); draw(d,pr); }).catch(function(e){ sb.disabled=false; sb.textContent='Submit'; toast(e.message+(e.payload&&e.payload.problems?': '+e.payload.problems.join('; '):''),true); }); };
      var cs=document.getElementById('ocsv'); if(cs)cs.onclick=function(){ var inp=document.createElement('input'); inp.type='file'; inp.accept='.csv,text/csv'; inp.onchange=function(){ var f=inp.files[0]; if(!f)return; var r=new FileReader(); r.onload=function(){ var n=0; String(r.result).split(/\r?\n/).forEach(function(line){ var c=line.split(/[,;\t]/).map(function(x){return x.replace(/^"|"$/g,'').trim();}); var sku=(c[0]||'').toUpperCase(), q=Math.round(Number(c[1])||0); if(byS[sku]&&q>0){ ORD.cart[sku]=q; n++; } }); saveCart(); toast(n+' line'+(n===1?'':'s')+' loaded from CSV'); draw(d,pr); }; r.readAsText(f); }; inp.click(); };
      var tp=document.getElementById('otpl'); if(tp)tp.onclick=function(){ var blob=new Blob(['sku,qty\n'+ps.slice(0,3).map(function(p){return p.sku+',';}).join('\n')],{type:'text/csv'}), u=URL.createObjectURL(blob), a=document.createElement('a'); a.href=u; a.download='dock-and-bay-order-template.csv'; document.body.appendChild(a); a.click(); a.remove(); };
    }
  }
  // ── MY ORDERS ──
  var OV={tab:'all',q:'',from:'',to:''};
  function vOrders(seg){ var m=main(); m.innerHTML='<h1 class="cp-h">My orders</h1><p class="cp-lead">Loading…</p>';
    orders().then(function(j){ var os=j.orders||[]; if(seg[0]){ var o=os.find(function(x){return String(x.id)===String(seg[0]);}); if(o)return detail(o); }
      var list=os.filter(function(o){ if(OV.tab==='open'&&!(o.bucket==='open'||o.bucket==='draft'))return false; if(OV.tab==='fulfilled'&&o.bucket!=='fulfilled')return false; if(OV.tab==='unpaid'&&!o.unpaid)return false; if(OV.from&&o.created<OV.from)return false; if(OV.to&&o.created>OV.to)return false; if(OV.q){ var q=OV.q.toLowerCase(); if([o.ref,o.number,o.company,o.customer,o.customer_po].join(' ').toLowerCase().indexOf(q)<0)return false; } return true; });
      m.innerHTML='<h1 class="cp-h">My orders</h1><p class="cp-lead">Open, fulfilled and unpaid in one list. Orders before the Fulfil cut-over carry a Xero invoice; later orders carry a Fulfil document.</p>'
        +'<div class="cp-bar">'+['all','open','fulfilled','unpaid'].map(function(t){return '<span class="cp-chip'+(OV.tab===t?' active':'')+'" data-t="'+t+'">'+t[0].toUpperCase()+t.slice(1)+'</span>';}).join('')+'<input class="cp-in" id="ovq" placeholder="order ref / PO / customer" value="'+esc(OV.q)+'" style="width:220px"><input class="cp-in" id="ovf" type="date" value="'+esc(OV.from)+'"><input class="cp-in" id="ovt" type="date" value="'+esc(OV.to)+'"><span class="tiny mut" style="margin-left:auto">'+list.length+' orders</span><button class="cp-btn" id="ovcsv">⬇ CSV</button></div>'
        +(list.map(orderRow).join('')||'<div class="cp-card mut">No orders match.</div>');
      m.querySelectorAll('.cp-chip[data-t]').forEach(function(c){ c.onclick=function(){ OV.tab=c.dataset.t; vOrders([]); }; });
      var q=document.getElementById('ovq'); q.onchange=function(){ OV.q=q.value; vOrders([]); }; document.getElementById('ovf').onchange=function(){ OV.from=this.value; vOrders([]); }; document.getElementById('ovt').onchange=function(){ OV.to=this.value; vOrders([]); };
      document.getElementById('ovcsv').onclick=function(){ var rows=['order,origin,company,customer,created,status,tracking,carrier,amount,currency,document'].concat(list.map(function(o){ return [o.ref,o.origin,o.company,o.customer,o.created,o.bucket+(o.unpaid?' unpaid':''),o.tracking,o.carrier,o.amount,o.currency,o.document.label].map(function(v){v=v==null?'':String(v);return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v;}).join(','); })); var blob=new Blob([rows.join('\n')],{type:'text/csv'}), u=URL.createObjectURL(blob), a=document.createElement('a'); a.href=u; a.download='orders.csv'; document.body.appendChild(a); a.click(); a.remove(); };
      function detail(o){ var tl=o.bucket==='draft'?['Submitted','Confirmation','Picked','Shipped']:['Confirmed','Picked','Shipped','Delivered']; var at=o.bucket==='draft'?1:(o.bucket==='fulfilled'?3:1);
        m.innerHTML='<div class="cp-bar"><a class="cp-btn sm" href="#/orders">← My orders</a></div><h1 class="cp-h">'+esc(o.ref)+(o.sample?' <span class="badge b-a">Sample</span>':'')+'</h1><p class="cp-lead">'+esc(o.customer||o.company||'')+' · created '+fd(o.created)+(o.customer_po?' · your PO '+esc(o.customer_po):'')+'</p>'
          +'<div class="cp-card"><div class="tl">'+tl.map(function(s,i){ return '<i class="'+(i<at?'on':i===at?'now':'')+'"></i>'+s; }).join('')+'</div><div class="kv" style="margin-top:12px"><b>Status</b><span>'+orderRow(o).match(/<span class="badge[^]*?<\/span>/)[0]+'</span><b>Channel</b><span>'+esc(o.channel||'')+(o.country?' · '+esc(o.country):'')+'</span>'+(o.tracking?'<b>Tracking</b><span>'+esc(o.carrier||'')+' '+esc(o.tracking)+'</span>':'')+(o.fulfilled_date?'<b>Shipped</b><span>'+fd(o.fulfilled_date)+'</span>':'')+(o.requested?'<b>Requested</b><span>'+fd(o.requested)+'</span>':'')+'<b>Amount</b><span>'+(o.sample?'non-invoiced':money(o.amount,o.currency)+(o.net&&o.net!==o.amount?' <span class="tiny mut">('+money(o.net,o.currency)+' ex tax)</span>':''))+'</span><b>Document</b><span>'+esc(o.document.label)+(o.document.note?' <span class="tiny mut">· '+esc(o.document.note)+'</span>':'')+'</span></div></div>'
          +'<div class="cp-card flush"><div class="tw"><table class="cp"><thead><tr><th>SKU</th><th class="num">Qty</th><th class="num">Price</th><th class="num">Amount</th></tr></thead><tbody>'+(o.lines||[]).map(function(l){ return '<tr><td class="mono">'+esc(l.sku)+'</td><td class="num">'+units(l.qty)+'</td><td class="num">'+(l.price!=null?money(l.price,o.currency):'')+'</td><td class="num">'+(l.amount!=null?money(l.amount,o.currency):'')+'</td></tr>'; }).join('')+'</tbody></table></div></div>'; }
    }).catch(function(e){ m.innerHTML='<div class="cp-card" style="color:var(--neg)">'+esc(e.message)+'</div>'; }); }
  // ── COMMISSION ──
  function vCommission(seg){ var m=main(); m.innerHTML='<h1 class="cp-h">Commission statement</h1><p class="cp-lead">Loading…</p>';
    api('/api/cp/commission'+(seg[0]?'?month='+encodeURIComponent(seg[0]):'')).then(function(j){ var runs=j.runs||[], run=j.run;
      m.innerHTML='<h1 class="cp-h">Commission statement</h1><p class="cp-lead">'+esc(j.group||'')+' · finalised runs only · a run covers invoices paid in the month. Amounts are sales value ex tax and ex shipping, net of credit notes; credit notes use the original order\'s rate.</p>'
        +(runs.length?'<div class="cp-bar"><select class="cp-in" id="cmonth">'+runs.map(function(r){return '<option value="'+esc(r.month)+'"'+(r.month===j.month?' selected':'')+'>'+esc(r.month)+' · '+esc(r.status)+'</option>';}).join('')+'</select>'+(run?'<span class="badge '+(run.status==='paid'?'b-g':'b-b')+'">'+(run.status==='paid'?'Paid '+fd(run.paid_at):'Finalised '+fd(run.finalised_at))+' · '+money(run.total,j.currency)+'</span>':'')+'</div>'
          +'<div class="cp-card flush"><div class="tw"><table class="cp"><thead><tr><th>Order / invoice</th><th>Customer</th><th>Paid</th><th class="num">Amount (net)</th><th class="num">Rate</th><th class="num">Commission</th><th class="num">Credit note</th><th class="num">Net</th><th>Status</th></tr></thead><tbody>'+(j.rows||[]).map(function(r){ return '<tr><td class="mono">'+esc(r.order_ref||'')+(r.invoice_ref?' · '+esc(r.invoice_ref):'')+'</td><td>'+esc(r.customer||'')+'</td><td>'+fd(r.paid)+'</td><td class="num">'+money(r.commissionable,j.currency)+'</td><td class="num">'+Number(r.rate)+' %</td><td class="num">'+money(r.commission,j.currency)+'</td><td class="num">'+(r.credit_note_ref?esc(r.credit_note_ref)+' '+money(r.credit_adj,j.currency):'')+'</td><td class="num"><b>'+money(r.net,j.currency)+'</b></td><td><span class="badge '+(r.status==='paid'?'b-g':'b-a')+'">'+esc(r.status)+'</span></td></tr>'; }).join('')+'<tr style="font-weight:700"><td colspan="7">Total '+esc(j.month||'')+'</td><td class="num">'+money((j.rows||[]).reduce(function(s,r){return s+Number(r.net||0);},0),j.currency)+'</td><td></td></tr></tbody></table></div></div>'
          :'<div class="cp-card mut">'+esc(j.note||'No finalised statements yet.')+'</div>');
      var sel=document.getElementById('cmonth'); if(sel)sel.onchange=function(){ location.hash='#/commission/'+sel.value; };
    }).catch(function(e){ m.innerHTML='<div class="cp-card" style="color:var(--neg)">'+esc(e.message)+'</div>'; }); }
  // ── MESSAGES ──
  function vMessages(seg){ var m=main(); m.innerHTML='<h1 class="cp-h">Messages</h1><p class="cp-lead">Loading…</p>';
    api('/api/cp/threads').then(function(j){ var ts=j.threads||[]; var cur=seg[0]?ts.find(function(t){return String(t.id)===String(seg[0]);}):ts[0];
      m.innerHTML='<h1 class="cp-h">Messages</h1><p class="cp-lead">Talk to the Dock &amp; Bay team here, with screenshots; the thread stays with your account.</p><div class="two"><div class="cp-card" style="padding:6px">'+(ts.map(function(t){ return '<div class="thread'+(cur&&t.id===cur.id?' on':'')+'" data-id="'+t.id+'"><div style="min-width:0"><b>'+esc(t.subject||'Conversation')+'</b>'+(t.unread_client?' <span class="badge b-r">'+t.unread_client+' new</span>':'')+'<div class="tiny mut" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">'+esc(t.preview||'')+'</div><div class="tiny faint">'+esc(t.last_at||'')+(t.context?' · '+esc(t.context):'')+'</div></div></div>'; }).join('')||'<div class="mut tiny" style="padding:8px">No conversations yet.</div>')+'<div style="padding:8px"><button class="cp-btn" id="mnew" style="width:100%">+ New message</button></div></div><div class="cp-card" id="mpane">'+(cur?'<div class="mut">Loading…</div>':'<div class="mut">Pick a conversation or start a new one.</div>')+'</div></div>';
      m.querySelectorAll('.thread[data-id]').forEach(function(t){ t.onclick=function(){ location.hash='#/messages/'+t.dataset.id; }; });
      document.getElementById('mnew').onclick=function(){ var pane=document.getElementById('mpane'); pane.innerHTML='<h3>New message</h3><div class="kv"><b>Subject</b><input class="cp-in" id="msub" placeholder="e.g. Line sheet · XL colour"><b>About</b><input class="cp-in" id="mctx" placeholder="order ref / SKU (optional)"><b>Message</b><textarea class="cp-in" id="mbody" rows="5" style="height:auto;padding:8px 12px"></textarea></div><div class="cp-bar" style="margin-top:10px"><input type="file" id="mfiles" multiple style="font-size:12px"><button class="cp-btn acc" id="msend">Send</button></div>';
        document.getElementById('msend').onclick=function(){ var b=this; b.disabled=true; readFiles(document.getElementById('mfiles')).then(function(atts){ return api('/api/cp/threads',{method:'POST',body:{subject:document.getElementById('msub').value,context:document.getElementById('mctx').value,body:document.getElementById('mbody').value,attachments:atts}}); }).then(function(r){ location.hash='#/messages/'+r.id; }).catch(function(e){ b.disabled=false; toast(e.message,true); }); }; };
      if(cur)api('/api/cp/threads/'+cur.id).then(function(d){ var pane=document.getElementById('mpane'); if(!pane)return; ME.unread=Math.max(0,(ME.unread||0)-(cur.unread_client||0)); var nb=document.querySelector('#cp-nav [data-t="messages"] .cnt'); if(nb){ if(ME.unread)nb.textContent=ME.unread; else nb.remove(); }
        pane.innerHTML='<h3>'+esc(d.thread.subject||'Conversation')+(d.thread.context?' <span class="mut tiny">· '+esc(d.thread.context)+'</span>':'')+'</h3>'+d.messages.map(function(x){ return '<div class="msg'+(x.sender_kind==='client'?' me':'')+'"><div class="who2">'+esc(x.sender_kind==='ops'?(x.sender||'Dock & Bay')+' (Dock & Bay)':x.sender||'You')+' · '+esc(x.at)+'</div>'+esc(x.body||'')+(x.files&&x.files.length?'<div>'+x.files.map(function(f){ return /^image\//.test(f.mime||'')?'<a href="/api/cp/attachment/'+f.id+'" target="_blank" rel="noopener"><img src="/api/cp/attachment/'+f.id+'" alt="'+esc(f.filename)+'" style="max-width:220px;max-height:180px;border-radius:8px;margin-top:6px;display:block"></a>':'<a class="att" href="/api/cp/attachment/'+f.id+'" target="_blank" rel="noopener">📎 '+esc(f.filename)+'</a>'; }).join('')+'</div>':'')+'</div>'; }).join('')+'<div class="cp-bar" style="margin:10px 0 0"><textarea class="cp-in" id="mreply" placeholder="Reply…" rows="2" style="flex:1 1 260px;height:auto;padding:8px 12px"></textarea><input type="file" id="mrfiles" multiple style="font-size:12px;max-width:180px"><button class="cp-btn acc" id="mrsend">Send</button></div>';
        document.getElementById('mrsend').onclick=function(){ var b=this; b.disabled=true; readFiles(document.getElementById('mrfiles')).then(function(atts){ return api('/api/cp/threads/'+cur.id+'/reply',{method:'POST',body:{body:document.getElementById('mreply').value,attachments:atts}}); }).then(function(){ vMessages([String(cur.id)]); }).catch(function(e){ b.disabled=false; toast(e.message,true); }); }; });
    }).catch(function(e){ m.innerHTML='<div class="cp-card" style="color:var(--neg)">'+esc(e.message)+'</div>'; }); }
  function readFiles(inp){ var fs=inp&&inp.files?Array.prototype.slice.call(inp.files):[]; return Promise.all(fs.slice(0,6).map(function(f){ return new Promise(function(res,rej){ if(f.size>8*1024*1024)return rej(new Error(f.name+' is over 8 MB')); var r=new FileReader(); r.onload=function(){ res({filename:f.name,mime:f.type||'application/octet-stream',data_base64:String(r.result).split(',')[1]}); }; r.onerror=function(){ rej(new Error('could not read '+f.name)); }; r.readAsDataURL(f); }); })); }
  boot();
})();
