// Token codemod for renderer functions: replaces inline hex colours inside the named functions with design tokens.
// Usage: node token_codemod.cjs <file> fn1,fn2,...   (prints per-function replacement counts; refuses functions that draw on canvas/SVG/PDF)
const fs=require('fs'); const [file,list]=process.argv.slice(2); const names=list.split(',');
const MAP={'#0f172a':'--nav','#1e293b':'--nav-2','#374151':'--nav-2','#111':'--ink','#111827':'--ink','#1a1a1a':'--ink','#0a0a0a':'--ink','#333':'--ink-soft','#334155':'--ink-soft','#1f2937':'--ink-soft','#444':'--muted','#475569':'--muted','#555':'--muted','#64748b':'--muted','#64758b':'--muted','#666':'--muted','#6b7280':'--muted','#4b5563':'--muted','#888':'--faint','#94a3b8':'--faint','#9ca3af':'--faint','#999':'--faint','#aaa':'--faint','#bbb':'--faint','#7c93b8':'--faint','#cbd5e1':'--line','#d0d0d0':'--line','#d1d5db':'--line','#ccc':'--line','#e2e8f0':'--line','#e5e7eb':'--line','#e0e0e0':'--line','#e8e8e8':'--line','#ddd':'--line','#dde3ea':'--line','#c3d4ee':'--line','#d5dae3':'--line','#eee':'--line2','#f1f1f1':'--line2','#eef2f7':'--line2','#f1f5f9':'--hover','#f3f4f6':'--hover','#f5f5f5':'--hover','#f8fafc':'--hover','#f9fafb':'--hover','#f7f8fb':'--hover','#1d4ed8':'--blue','#2563eb':'--blue','#3b82f6':'--blue','#1e40af':'--blue-ink','#1e3a8a':'--blue-ink','#dbeafe':'--blue-soft','#eff6ff':'--blue-soft','#dc2626':'--neg','#b91c1c':'--neg','#ef4444':'--neg','#991b1b':'--neg','#7f1d1d':'--neg','#fee2e2':'--neg-bg','#fef2f2':'--neg-bg','#fecaca':'--neg-cell','#fca5a5':'--neg-cell','#16a34a':'--pos','#166534':'--pos','#15803d':'--pos','#22c55e':'--pos','#14532d':'--pos','#dcfce7':'--pos-bg','#ecfdf5':'--pos-bg','#f0fdf4':'--pos-bg','#bbf7d0':'--pos-bg','#86efac':'--pos-bg','#b45309':'--amber','#92400e':'--amber','#d97706':'--amber','#9a3412':'--amber','#854d0e':'--amber','#fef3c7':'--amber-bg','#fffbeb':'--amber-bg','#fef9c3':'--amber-bg','#fde68a':'--amber-bg','#fbbf24':'--prod','#f59e0b':'--prod','#7c3aed':'--violet','#5b21b6':'--violet','#6d28d9':'--violet','#4f46e5':'--violet','#6366f1':'--violet','#ede9fe':'--violet-bg','#f5f3ff':'--violet-bg','#eef2ff':'--violet-bg'};
let src=fs.readFileSync(file,'utf8'); const js=src;
const re=/^\s{0,4}(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(|^\s{0,4}(?:var|const|let)\s+([A-Za-z_$][\w$]*)\s*=\s*function\s*\(/gm;
const marks=[]; let m; while((m=re.exec(js))){ marks.push({name:m[1]||m[2],at:m.index}); }
let out='', cursor=0, report=[];
marks.forEach((mk,i)=>{ if(!names.includes(mk.name))return; const s=mk.at, e=(marks[i+1]?marks[i+1].at:js.length); let chunk=js.slice(s,e);
  if(/fillStyle|strokeStyle|jsPDF|rasterize|toDataURL|createElementNS/i.test(chunk)){ report.push(mk.name+': SKIPPED (draws)'); return; }
  let n=0; const nc=chunk.replace(/(?<!fill="|stroke="|fill='|stroke=')#([0-9a-fA-F]{6}|[0-9a-fA-F]{3})(?![0-9a-fA-F\w-])/g,(h)=>{ const k=h.toLowerCase(); const t=MAP[k]; if(!t)return h; n++; return 'var('+t+')'; });
  out+=js.slice(cursor,s)+nc; cursor=e; report.push(mk.name+': '+n+' colours → tokens'); });
out+=js.slice(cursor);
fs.writeFileSync(file,out); console.log(report.join('\n')); console.log('unresolved hex left in those fns is fine (no token) — see report above');
