-- 017_deposits_surrogate_key.sql — deposits keyed by surrogate id, not reference (v20.4)
--
-- The full DEPOSITS-and-OTHER working list shows that `reference` is NOT a key:
--   • 159 "Other" sundry payments (DHL/Intertek/freight fees) have NO reference — they tie to a
--     PO by description, not a deposit ref.
--   • Some deposit refs repeat (e.g. P19-UK-XR appears 3×) — genuinely separate installments.
-- So reference cannot be the primary key. Move to a surrogate `id`; keep reference as a plain,
-- nullable, non-unique attribute (still the join key from purchase_orders.deposit_ref where set).
-- Also add xero_account_code, which the source carries and we were dropping.

ALTER TABLE planner.deposits ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE planner.deposits DROP CONSTRAINT IF EXISTS deposits_pkey;
ALTER TABLE planner.deposits ADD PRIMARY KEY (id);
ALTER TABLE planner.deposits ALTER COLUMN reference DROP NOT NULL;
CREATE INDEX IF NOT EXISTS deposits_reference_idx ON planner.deposits(reference);
ALTER TABLE planner.deposits ADD COLUMN IF NOT EXISTS xero_account_code text;
