-- 019_landed_cost_settings.sql — landed-cost rate tables + per-PO/product fields (v20.9)
--
-- Estimated landed cost = goods (order-plan Σ qty×cost) + freight + import duty + import tax.
--   • Import DUTY varies by product AND destination country → stored per product-country
--     (planner.product_countries.duty_pct). Computed per PO line.
--   • Import TAX/VAT is one rate per destination country → maintained in Settings
--     (planner.import_tax_rates), applied to the landed base.
--   • FREIGHT baseline is a rate card by destination × container size (planner.freight_rates);
--     the actual Flexport quote is preferred when a shipment is linked (handled in the query).
-- A PO's container_size drives which freight-rate row applies.

CREATE TABLE IF NOT EXISTS planner.import_tax_rates (
  country    text PRIMARY KEY,            -- destination (UK/US/EU/AU/CA…)
  tax_pct    numeric,
  base       text DEFAULT 'landed',       -- 'landed' (goods+duty+freight) or 'goods'
  notes      text,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS planner.freight_rates (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destination    text,
  container_size text,                     -- 20ft / 40ft / 40HC / LCL / Air
  cost           numeric,
  currency       text DEFAULT 'USD',
  notes          text,
  updated_at     timestamptz DEFAULT now()
);

ALTER TABLE planner.product_countries ADD COLUMN IF NOT EXISTS duty_pct numeric;
ALTER TABLE planner.purchase_orders   ADD COLUMN IF NOT EXISTS container_size text;

-- Seed the rate tables with the destinations / sizes in use, values blank for Ben to fill in.
INSERT INTO planner.import_tax_rates(country,tax_pct,base) VALUES
  ('UK',20,'landed'),('EU',20,'landed'),('US',0,'landed'),('AU',10,'landed'),('CA',5,'landed')
ON CONFLICT (country) DO NOTHING;

INSERT INTO planner.freight_rates(destination,container_size,cost,currency)
SELECT d, s, NULL, 'USD'
FROM (VALUES ('UK'),('EU'),('US'),('AU'),('CA')) dd(d),
     (VALUES ('20ft'),('40ft'),('40HC'),('LCL'),('Air')) ss(s)
WHERE NOT EXISTS (SELECT 1 FROM planner.freight_rates);
