-- 020_duty_rates.sql — editable import-duty rate card by product category × destination (v20.11)
--
-- Duty varies by product and destination. The precise source of truth is per-product per-country
-- (product_countries.duty_pct, added in 019), but maintaining that for every SKU is heavy. This
-- card gives an editable default by *category* × country that the landed-cost calc falls back to
-- when a product has no explicit duty %. Seeded with rough textile-trade defaults — placeholders
-- for Ben to correct in Settings.

CREATE TABLE IF NOT EXISTS planner.duty_rates (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category   text,
  country    text,                    -- destination (UK/US/EU/AU/CA…) — matches purchase_orders.country_code
  duty_pct   numeric,
  notes      text,
  updated_at timestamptz DEFAULT now(),
  UNIQUE (category, country)
);

-- Seed every existing product category × the destinations in use with a country-level textile
-- default (clearly flagged as dummy). Idempotent.
INSERT INTO planner.duty_rates (category, country, duty_pct, notes)
SELECT c.category, d.country, d.pct, 'dummy textile default — verify'
FROM (SELECT DISTINCT category FROM planner.products WHERE category IS NOT NULL) c
CROSS JOIN (VALUES ('UK',12),('EU',12),('US',9),('AU',5),('CA',18)) d(country,pct)
ON CONFLICT (category, country) DO NOTHING;
