-- 040_air_freight_rates.sql — tiered air-freight rate card (v20.146)
--
-- Air freight is priced per-kg by total shipment weight, the SAME for all destinations (unlike sea, which is
-- per-container × country). Tiers: 0–30kg $15/kg, 30–100kg $10/kg, 100–400kg $8/kg, 400kg+ $7/kg. The shipment
-- AIR cost estimate = weight × the matching tier's rate. The 'Air' row in freight_rates is no longer used
-- (that table is now sea-only).
CREATE TABLE IF NOT EXISTS planner.air_freight_rates (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  min_kg      numeric NOT NULL,
  max_kg      numeric NOT NULL,
  rate_per_kg numeric,
  updated_at  timestamptz DEFAULT now()
);
INSERT INTO planner.air_freight_rates (min_kg, max_kg, rate_per_kg)
SELECT * FROM (VALUES (0,30,15),(30,100,10),(100,400,8),(400,99999,7)) v(a,b,c)
WHERE NOT EXISTS (SELECT 1 FROM planner.air_freight_rates);
