-- 043_supplier_portal.sql — supplier portal: approved users, magic-link auth, notes, staged submissions, attachments (v20.158)
--
-- A supplier logs into a scoped portal (/portal) via a magic link. CONFIG ▸ Portal Users is the approved list
-- (email ↔ supplier). The portal only ever shows the authenticated supplier's own POs/deposits.
--   • supplier_portal_users — the approved list (email mapped to one supplier).
--   • portal_magic_tokens   — one-time, expiring login tokens (dev stub now; Diviyaj wires real email).
--   • portal_sessions       — session after a magic token is consumed (Diviyaj can swap for signed cookies).
--   • supplier_notes        — per-PO comments (post immediately; visible both sides).
--   • supplier_submissions  — supplier write-backs. tracking/carrier apply directly (status=applied);
--                             completion_date/invoice_value are staged (status=pending) for internal one-click apply.
--   • portal_attachments    — uploaded invoice docs (bytea in Postgres for now; Diviyaj may move to Supabase Storage).

CREATE TABLE IF NOT EXISTS planner.supplier_portal_users (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email        text NOT NULL,
  supplier_id  bigint REFERENCES planner.suppliers(id),
  supplier_name text,
  contact_name text,
  active       boolean NOT NULL DEFAULT true,
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS supplier_portal_users_email_ux ON planner.supplier_portal_users (lower(email));

CREATE TABLE IF NOT EXISTS planner.portal_magic_tokens (
  token      text PRIMARY KEY,
  email      text NOT NULL,
  created_at timestamptz DEFAULT now(),
  expires_at timestamptz NOT NULL,
  used_at    timestamptz
);

CREATE TABLE IF NOT EXISTS planner.portal_sessions (
  token       text PRIMARY KEY,
  email       text NOT NULL,
  supplier_id bigint,
  created_at  timestamptz DEFAULT now(),
  expires_at  timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS planner.supplier_notes (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po          text,
  supplier_id bigint,
  author_email text,
  author_kind text DEFAULT 'supplier',      -- supplier | internal
  body        text NOT NULL,
  created_at  timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS planner.supplier_submissions (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id  bigint,
  po           text,
  shipment_ref text,
  kind         text NOT NULL,               -- completion_date | invoice_value | tracking | carrier
  value        text,
  attachment_id bigint,
  status       text NOT NULL DEFAULT 'pending',  -- pending | applied | dismissed
  submitted_by text,
  submitted_at timestamptz DEFAULT now(),
  applied_by   text,
  applied_at   timestamptz,
  note         text
);

CREATE TABLE IF NOT EXISTS planner.portal_attachments (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po          text,
  supplier_id bigint,
  filename    text,
  mime        text,
  byte_size   int,
  data        bytea,
  uploaded_by text,
  uploaded_at timestamptz DEFAULT now()
);
